### ISSUE TITLE
是不是要充值快豆。

### ISSUE THREAD

**Issue by cechaodeng** [testerSunshine/12306#104]

**Comment by 1104049235** [comment]
1块钱够用很久

**Comment by rainstorm0506** [comment]
运行run.py报错。
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/home/vagrant/labs/Ticket/config/emailConf.py", line 5, in <module>
    from config.ticketConf import _get_yaml
  File "/home/vagrant/labs/Ticket/config/ticketConf.py", line 4, in <module>
    import yaml
ImportError: No module named yaml

**Comment by mingmingzhuding** [comment]
@rainstorm0506 先安装 requirements.txt里的模块

**Comment by Lancelothe** [comment]
> 1块钱够用很久

请问注册若快什么账号？ 普通用户还是开发者账号？

**Comment by sherlockfff** [comment]
买了快豆，也配置了账号，但是启动的时候不生效呢？还是需要手动输入验证码位置

**Comment by testerSunshine** [comment]
已更新本地识别
