### ISSUE TITLE
run.py运行出现No module named yaml

### ISSUE THREAD

**Issue by rainstorm0506** [testerSunshine/12306#111]
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/home/vagrant/labs/Ticket/config/emailConf.py", line 5, in <module>
    from config.ticketConf import _get_yaml
  File "/home/vagrant/labs/Ticket/config/ticketConf.py", line 4, in <module>
    import yaml
ImportError: No module named yaml

**Comment by testerSunshine** [comment]
@rainstorm0506  https://github.com/testerSunshine/12306/issues/91
