### ISSUE TITLE
运行出错，KeyError: 'open_time'

### ISSUE THREAD

**Issue by JamesMarts** [testerSunshine/12306#114]
`C:\Users\lijuw\PycharmProjects\12306>python run.py
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "C:\Users\lijuw\PycharmProjects\12306\init\select_ticket_info.py", line 50, in __init__
    self.arrival_time, self.take_time, self.order_model, self.open_time = self.get_ticket_info()
  File "C:\Users\lijuw\PycharmProjects\12306\init\select_ticket_info.py", line 89, in get_ticket_info
    open_time = ticket_info_config["open_time"]
KeyError: 'open_time'
`

**Comment by JamesMarts** [comment]
已解决

**Comment by Guobaolou** [comment]
请问是怎么解决的啊
