### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by li8911255** [testerSunshine/12306#14]
正在获取cookie
下载验证码...
验证码通过,开始登录..
登录成功
12306接口无响应，正在重试
Traceback (most recent call last):
  File "/Users/lizhen/Desktop/12306/run.py", line 11, in <module>
    run()
  File "/Users/lizhen/Desktop/12306/run.py", line 7, in run
    select_ticket_info.select().main()
  File "/Users/lizhen/Desktop/12306/init/select_ticket_info.py", line 630, in main
    self.call_login()
  File "/Users/lizhen/Desktop/12306/init/select_ticket_info.py", line 627, in call_login
    login.go_login()
  File "/Users/lizhen/Desktop/12306/init/login.py", line 195, in go_login
    if self.getUserName(uamtk):
  File "/Users/lizhen/Desktop/12306/init/login.py", line 169, in getUserName
    if "result_code" in uamauthclientResult and uamauthclientResult["result_code"] == 0:
TypeError: argument of type 'NoneType' is not iterable

**Comment by testerSunshine** [comment]
已修复，用最新代码
