### ISSUE TITLE
报错了。。最后gbk的问题解决方法没起效果。。

### ISSUE THREAD

**Issue by Guobaolou** [testerSunshine/12306#141]
Traceback (most recent call last):
  File "E:/学子/python/12306-master/12306-master/init/select_ticket_info.py", line 312, in <module>
    s = select()
  File "E:/学子/python/12306-master/12306-master/init/select_ticket_info.py", line 54, in __init__
    self.arrival_time, self.take_time, self.order_model, self.open_time = self.get_ticket_info()
  File "E:/学子/python/12306-master/12306-master/init/select_ticket_info.py", line 72, in get_ticket_info
    ticket_info_config = _get_yaml()
  File "E:\学子\python\12306-master\12306-master\config\ticketConf.py", line 14, in _get_yaml
    s = yaml.load(f)
  File "E:\Program Files\Anaconda\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "E:\Program Files\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "E:\Program Files\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\Program Files\Anaconda\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "E:\Program Files\Anaconda\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 39: illegal multibyte sequence

**Comment by xinhuoniepan** [comment]
select_ticket_info.py -> result = open(path) 改为    result = open(path,'r', encoding='UTF-8')
ticketConf.py -> f = open(path)  改为  f = open(path,'r', encoding='UTF-8')
