### ISSUE TITLE
LookupError: unknown encoding: cp65001

### ISSUE THREAD

**Issue by dancelset** [testerSunshine/12306#15]
********************
正在获取cookie
下载验证码...
验证码识别坐标为271,67,289,158
Traceback (most recent call last):
  File "F:\12306-master\run.py", line 11, in <module>
    run()
  File "F:\12306-master\run.py", line 7, in run
    select_ticket_info.select().main()
  File "F:\12306-master\init\select_ticket_info.py", line 631, in main
    self.call_login()
  File "F:\12306-master\init\select_ticket_info.py", line 628, in call_login
    self.login.go_login()
  File "F:\12306-master\init\login.py", line 218, in go_login
    if self.codeCheck():
  File "F:\12306-master\init\login.py", line 139, in codeCheck
    print(fresult["result_message"])
LookupError: unknown encoding: cp65001

**Comment by dancelset** [comment]
新问题，老的解决了，新问题

**Comment by dancelset** [comment]
解决了，是yaml格式没搞对，true写成了小写

**Comment by testerSunshine** [comment]
那我关了
