### ISSUE TITLE
验证码结果错误

### ISSUE THREAD

**Issue by cnhua5** [testerSunshine/12306#16]
E:\work\openSource\12306>run.py
********************
褰撳墠閰嶇疆锛氬嚭鍙戠珯锛氫笂娴?
鍒拌揪绔欙細鍚堣偉鍗?
涔樿溅鏃ユ湡锛歔'2018-02-13']
鍧愬腑锛氫簩绛夊骇
鏄惁鏈夌エ鑷姩鎻愪氦锛歍rue
涔樿溅浜猴細浣欐偊
鍒锋柊闂撮殧锛?.1
鍊欓€夎喘涔拌溅娆★細G7268,G7232,D3064,G576,D952,G676,D2216,G9434,D3022,G7372,D956,G7564,G9502,D3060,D3090,D3068
鏈紑濮嬪埛绁ㄩ棿闅旀椂闂达細0.3
鍍靛案绁ㄥ叧灏忛粦灞嬫椂闀匡細3

********************
姝ｅ湪鑾峰彇cookie
涓嬭浇楠岃瘉鐮?..
楠岃瘉鐮侀€氳繃,寮€濮嬬櫥褰?.
12306鎺ュ彛鏃犲搷搴旓紝姝ｅ湪閲嶈瘯
Traceback (most recent call last):
  File "E:\work\openSource\12306\run.py", line 11, in <module>
    run()
  File "E:\work\openSource\12306\run.py", line 7, in run
    select_ticket_info.select().main()
  File "E:\work\openSource\12306\init\select_ticket_info.py", line 630, in main
    self.call_login()
  File "E:\work\openSource\12306\init\select_ticket_info.py", line 627, in call_login
    login.go_login()
  File "E:\work\openSource\12306\init\login.py", line 198, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "E:\work\openSource\12306\init\login.py", line 140, in baseLogin
    if 'result_code' in tresult and tresult["result_code"] == 0:
TypeError: argument of type 'NoneType' is not iterable

**Comment by testerSunshine** [comment]
已修改，用最新的代码
