### ISSUE TITLE
> 下单接口: 2

### ISSUE THREAD

**Issue by walker4753** [testerSunshine/12306#176]
> 下单接口: 2
> 下单模式: 2
> 预售踩点时间:13:00:00 Traceback (most recent call last):
> File "run.py", line 15, in 
> run()
> File "run.py", line 7, in run
> select_ticket_info.select().main()
> File "C:\Users\huang\Downloads\12306-master\init\select_ticket_info.py", line 50, in **init**
> self.arrival_time, self.take_time, self.order_model, self.open_time, self.is_proxy = self.get_ticket_info()
> File "C:\Users\huang\Downloads\12306-master\init\select_ticket_info.py", line 116, in get_ticket_info
> open_time,
> IOError: [Errno 0] Error

_Originally posted by @walker4753 in https://github.com/testerSunshine/12306/issue_comments#issuecomment-453754648_

**Comment by walker4753** [comment]
> > 下单接口: 2
> > 下单模式: 2
> > 预售踩点时间:13:00:00 Traceback (most recent call last):
> > File "run.py", line 15, in
> > run()
> > File "run.py", line 7, in run
> > select_ticket_info.select().main()
> > File "C:\Users\huang\Downloads\12306-master\init\select_ticket_info.py", line 50, in **init**
> > self.arrival_time, self.take_time, self.order_model, self.open_time, self.is_proxy = self.get_ticket_info()
> > File "C:\Users\huang\Downloads\12306-master\init\select_ticket_info.py", line 116, in get_ticket_info
> > open_time,
> > IOError: [Errno 0] Error
> 
> _Originally posted by @walker4753 in https://github.com/testerSunshine/12306/issue_comments#issuecomment-453754648_
