### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

### ISSUE THREAD

**Issue by StayY** [testerSunshine/12306#198]
**************************************************
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 50, in __init__
    self.arrival_time, self.take_time, self.order_model, self.open_time, self.is_proxy = self.get_ticket_info()
  File "/root/12306/init/select_ticket_info.py", line 98, in get_ticket_info
    print(u"检查当前python版本为：{}，目前版本只支持2.7.10-2.7.15".format(sys.version.split(" ")[0]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by StayY** [comment]
如何解决？
