### ISSUE TITLE
python2.7 TypeError 是少装了什么吗？还是只能在windows 下运行？

### ISSUE THREAD

**Issue by hisammy** [testerSunshine/12306#21]
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/data/study_python/12306/init/select_ticket_info.py", line 29, in __init__
    self.from_station, self.to_station, self.station_dates, self._station_seat, self.is_more_ticket, self.ticke_peoples, self.select_refresh_interval, self.station_trains, self.expect_refresh_interval, self.ticket_black_list_time = self.get_ticket_info()
  File "/data/study_python/12306/init/select_ticket_info.py", line 68, in get_ticket_info
    ",".join(station_trains),
TypeError

**Comment by hisammy** [comment]
配置问题
