### ISSUE TITLE
No module named ordered_dict

### ISSUE THREAD

**Issue by muyi00** [testerSunshine/12306#217]
root@instance-si74mvy8:~/12306# sudo python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.pushbearConf import sendPushBear
  File "/root/12306/config/pushbearConf.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 92, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

**Comment by testerSunshine** [comment]
urllib3的依赖，可以去装下
