### ISSUE TITLE
成功后出现乱码

### ISSUE THREAD

**Issue by ningxiaoxiao** [testerSunshine/12306#219]
查询到有余票，尝试提交订单
鎮ㄨ繕鏈夋湭澶勭悊鐨勮鍗曪紝璇锋偍鍒?a href="../view/train_order.html">[鏈畬鎴愯鍗昡</a>杩涜澶勭悊!Traceback (most recent call last):
  File "run.py", line 21, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "C:\Users\xiaoxiao\12306\12306\init\select_ticket_info.py", line 311, in main
    print(e)
IOError: [Errno 0] Error
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
C:\Users\xiaoxiao\12306\12306>python2 run.py
**************************************************

**Comment by testerSunshine** [comment]
https://github.com/testerSunshine/12306/issues/159
