### ISSUE TITLE
提交订单成功后抛异常，但是不影响订单生成，是不是买到票的结果就是抛这个异常啊，逼死强迫症

### ISSUE THREAD

**Issue by wxg8009** [testerSunshine/12306#221]
邮件已通知, 请查收
已下发 pushbear 微信通知, 请查收
鎭枩鎮ㄨ绁ㄦ垚鍔燂紝璁㈠崟鍙蜂负锛欵067333971, 璇风珛鍗虫墦寮€娴忚鍣ㄧ櫥褰?2306锛岃闂€樻湭瀹屾垚璁㈠崟鈥欙紝鍦?0鍒嗛挓鍐呭畬鎴愭敮浠?Traceback (most recent call last):
  File ".\run.py", line 19, in <module>
    run()
  File ".\run.py", line 8, in run
    select_ticket_info.select().main()
  File "E:\Python\12306\init\select_ticket_info.py", line 304, in main
    print(e)
IOError: [Errno 0] Error

我的该文件304行是下面第二行：
            except ticketIsExitsException as e:
                print(e)

**Comment by wxg8009** [comment]
if data and data.get("orderId", ""):
                        sendEmail(ticket.WAIT_ORDER_SUCCESS.format(
                            data.get("orderId", "")))
                        sendPushBear(ticket.WAIT_ORDER_SUCCESS.format(
                            data.get("orderId", "")))
                        raise ticketIsExitsException(ticket.WAIT_ORDER_SUCCESS.format(
                            data.get("orderId")))
找到了，当我没说。。。。
