### ISSUE TITLE
我的python存在字符乱码的问题

### ISSUE THREAD

**Issue by zhaowei699** [testerSunshine/12306#234]
C:\scripts\12306_py2\12306-master\12306-master>python run.py
**************************************************
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "C:\scripts\12306_py2\12306-master\12306-master\init\select_ticket_info.py", line 50, in __init__
    self.arrival_time, self.take_time, self.order_model, self.open_time, self.is_proxy = self.get_ticket_info()
  File "C:\scripts\12306_py2\12306-master\12306-master\init\select_ticket_info.py", line 98, in get_ticket_info
    print(u"µúÇµƒÑσ╜ôσëìpythonτëêµ£¼Σ╕║∩╝Ü{}∩╝îτ¢«σëìτëêµ£¼σÅ¬µö»µîü2.7.10-2.7.15".format(sys.version.split(" ")[0]))
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

C:\scripts\12306_py2\12306-master\12306-master>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by testerSunshine** [comment]
https://blog.csdn.net/alien_lily/article/details/83009153
