### ISSUE TITLE
ImportError: DLL load failed: �Ҳ���ָ����ģ�顣

### ISSUE THREAD

**Issue by Xjhqc** [testerSunshine/12306#237]
运行run.py的时候报错：
Traceback (most recent call last):
  File "D:/MyPython/12306/run.py", line 4, in <module>
    from init import select_ticket_info
  File "D:\MyPython\12306\init\select_ticket_info.py", line 19, in <module>
    from init.login import GoLogin
  File "D:\MyPython\12306\init\login.py", line 6, in <module>
    from inter.GetRandCode import getRandCode
  File "D:\MyPython\12306\inter\GetRandCode.py", line 2, in <module>
    from PIL import Image
  File "D:\software\anaconda2\lib\site-packages\PIL\Image.py", line 58, in <module>
    from . import _imaging as core
ImportError: DLL load failed: �Ҳ���ָ����ģ�顣

**Comment by Xjhqc** [comment]
换了pillow==5.4.1解决了
