### ISSUE TITLE
pycharm跑通了 终端跑不通

### ISSUE THREAD

**Issue by bengdan** [testerSunshine/12306#24]
root@jay:~# python /root/12306/run.py 
********************
当前配置：出发站：北京西
到达站：武汉
乘车日期：['2018-02-11']
坐席：二等座
是否有票自动提交：True
乘车人：张英杰
刷新间隔：0.5
候选购买车次：G83
未开始刷票间隔时间：0.1
僵尸票关小黑屋时长：3

********************
正在获取cookie
下载验证码...
验证码识别坐标为268,73
验证码通过,开始登录..
正在获取cookie
下载验证码...
验证码识别坐标为173,64,241,141
验证码通过,开始登录..
登录成功
欢迎 张英杰 登录
Traceback (most recent call last):
  File "/root/12306/run.py", line 11, in <module>
    run()
  File "/root/12306/run.py", line 7, in run
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 632, in main
    from_station, to_station = self.station_table(self.from_station, self.to_station)
  File "/root/12306/init/select_ticket_info.py", line 119, in station_table
    result = open('station_name.txt')
IOError: [Errno 2] No such file or directory: 'station_name.txt'
root@jay:~#

**Comment by a-wing** [comment]
cd /root/12306/ && python2 run.py
