### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by dreamsleet** [testerSunshine/12306#265]
验证码识别坐标为112,149
None
None
None
None
None
None
None
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 207, in main
    self.call_login()
  File "/root/12306/init/select_ticket_info.py", line 167, in call_login
    self.login.go_login()
  File "/root/12306/init/login.py", line 156, in go_login
    if self.codeCheck():
  File "/root/12306/init/login.py", line 57, in codeCheck
    fresult = eval(fresult.split("(")[1].split(")")[0])
AttributeError: 'dict' object has no attribute 'split'

**Comment by ifirework** [comment]
你这个最后咋整了？

**Comment by dreamsleet** [comment]
@ifirework  全部干掉重新来过  估计是修改配置文件时那里格式有问题

**Comment by lisiyuan201** [comment]
全部干掉重新来过，具体应该怎么处理呢？

**Comment by lisiyuan201** [comment]
验证码通过,开始登录..
None
登录成功
None
None
需要验证码
None
None
None
None
None
None
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "D:\Program Files\12306-master\init\select_ticket_info.py", line 207, in main
    self.call_login()
  File "D:\Program Files\12306-master\init\select_ticket_info.py", line 167, in call_login
    self.login.go_login()
  File "D:\Program Files\12306-master\init\login.py", line 146, in go_login
    devicesId = eval(devicesIdRsp.split("(")[1].split(")")[0].replace("'", ""))["dfp"]
AttributeError: 'dict' object has no attribute 'split'

D:\Program Files\12306-master>

**Comment by dreamsleet** [comment]
@lisiyuan201 就是把之前的删除重新克隆和配置啊

**Comment by lisiyuan201** [comment]
哦哦，明白，我再试一次

**Comment by dreamsleet** [comment]
注意配置yml文件时严格遵循格式

**Comment by lisiyuan201** [comment]
问题已解决：将之前的删除后，再克隆配置，现在已经可以了，辛苦了楼主。

**Comment by lisiyuan201** [comment]
额，还是没有解决，发现在ticket_config处，如果填写了乘车人，就会出现上面的问题，如果不填写，就可以抢票，但不知可不可以完成抢票订单？
 # 乘车人(list) 多个乘车人ex:
  # - "张三"
  # - "李四"
  ticke_peoples:
    - ""   ##此外若填写，则出现AttributeError: 'dict' object has no attribute 'split'
