### ISSUE TITLE
项目运行出现错误，求解

### ISSUE THREAD

**Issue by nishizhumagu** [testerSunshine/12306#267]
`Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/Users/fanyue/Documents/GitHub/12306/init/select_ticket_info.py", line 207, in main
    self.call_login()
  File "/Users/fanyue/Documents/GitHub/12306/init/select_ticket_info.py", line 167, in call_login
    self.login.go_login()
  File "/Users/fanyue/Documents/GitHub/12306/init/login.py", line 156, in go_login
    if self.codeCheck():
  File "/Users/fanyue/Documents/GitHub/12306/init/login.py", line 57, in codeCheck
    fresult = eval(fresult.split("(")[1].split(")")[0])
AttributeError: 'dict' object has no attribute 'split'`

**Comment by xiaoke0O** [comment]
同样的问题

**Comment by ifirework** [comment]
都解决了吗？这个问题

**Comment by xiaoke0O** [comment]
> 都解决了吗？这个问题
将/init/login.py文件中的`devicesId = eval(devicesIdRsp.split("(")[1].split(")")[0].replace("'", ""))["dfp"]`改为`devicesId = "kyfw.12306.cn"`可临时解决

**Comment by MyEclipseQZ** [comment]
改了也不好使

**Comment by testerSunshine** [comment]
自己可以去浏览器抓取RAIL_DEVICEID，填入即可解决问题，已更新教程 @Zero0Infinite 这个同学的教程也可以
