### ISSUE TITLE
下载验证码失败

### ISSUE THREAD

**Issue by justingboy** [testerSunshine/12306#270]
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
需要验证码
下载验证码...
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    run12306GrabTicket()
  File "run.py", line 9, in run12306GrabTicket
    select_ticket_info.select().main()
  File "/home/python/12306New/init/select_ticket_info.py", line 207, in main
    self.call_login()
  File "/home/python/12306New/init/select_ticket_info.py", line 167, in call_login
    self.login.go_login()
  File "/home/python/12306New/init/login.py", line 150, in go_login
    result = getPassCodeNewOrderAndLogin1(session=self.session, imgType="login")
  File "/home/python/12306New/inter/GetPassCodeNewOrderAndLogin.py", line 56, in getPassCodeNewOrderAndLogin1
    result = eval(codeImgUrlRsp.split("(")[1].split(")")[0]).get("image")
AttributeError: 'dict' object has no attribute 'split'

**Comment by justingboy** [comment]
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
需要验证码
下载验证码...
验证码：{'code': 99999, 'message': '重试次数达到上限'}
Traceback (most recent call last):
File "run.py", line 27, in 
run12306GrabTicket()
File "run.py", line 9, in run12306GrabTicket
select_ticket_info.select().main()
File "/home/python/12306New/init/select_ticket_info.py", line 207, in main
self.call_login()
File "/home/python/12306New/init/select_ticket_info.py", line 167, in call_login
self.login.go_login()
File "/home/python/12306New/init/login.py", line 150, in go_login
result = getPassCodeNewOrderAndLogin1(session=self.session, imgType="login")
File "/home/python/12306New/inter/GetPassCodeNewOrderAndLogin.py", line 56, in getPassCodeNewOrderAndLogin1
result = eval(codeImgUrlRsp.split("(")[1].split(")")[0]).get("image")
AttributeError: 'dict' object has no attribute 'split'
