### ISSUE TITLE
Ubuntu环境下run.py报错

### ISSUE THREAD

**Issue by cwj00317** [testerSunshine/12306#284]
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/home/cwj/12306/init/select_ticket_info.py", line 50, in __init__
    self.auto_code_type = _get_yaml()["auto_code_type"]
KeyError: 'auto_code_type'

求各位大佬解答。。。

**Comment by testerSunshine** [comment]
你的auto_code_type没填
