### ISSUE TITLE
windows环境下 出一堆错 不知道是什么原因

### ISSUE THREAD

**Issue by lll423** [testerSunshine/12306#299]
提示以下错误 不知道是什么原因

本次待筛选cdn总数为1857, 筛选时间大约为5-10min
cookie获取中
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
PermissionError: [WinError 5] 拒绝访问。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\download\12306-master\run.py", line 20, in <module>
    run()
  File "E:\download\12306-master\run.py", line 8, in run
    select_ticket_info.select().main()
  File "E:\download\12306-master\init\select_ticket_info.py", line 147, in main
    getDrvicesID(self)
  File "E:\download\12306-master\config\getCookie.py", line 12, in getDrvicesID
    driver = webdriver.Chrome(TickerConfig.CHROME_PATH)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'Application' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by TimoYoung** [comment]
chromedriver 没设好吧？

**Comment by lll423** [comment]
楼上正解，但同事的一台win7提示  无法安装tensorflow   不知道是何原因

**Comment by ShichaoJin** [comment]
解决方案 https://stackoverflow.com/questions/47148872/webdrivers-executable-may-have-wrong-permissions-please-see-https-sites-goo
