### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ZhongqiXiao** [testerSunshine/12306#31]
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "J:\Git-Repository\12306\12306\init\select_ticket_info.py", line 29, in __init__
    self.from_station, self.to_station, self.station_dates, self._station_seat, self.is_more_ticket, self.ticke_peoples, self.select_refresh_interval, self.station_trains, self.ticket_black_list_time = self.get_ticket_info()
  File "J:\Git-Repository\12306\12306\init\select_ticket_info.py", line 71, in get_ticket_info
    ticket_black_list_time,
IOError: [Errno 22] Invalid argument

**Comment by testerSunshine** [comment]
车次配置问题，仔细检查车次配置
