### ISSUE TITLE
使用COOKIE_TYPE 模式1，出现错误情况

### ISSUE THREAD

**Issue by Alion548** [testerSunshine/12306#318]
``` bash
运行环境：
Linux 3daf37714af0 5.2.11-200.fc30.x86_64 #1 SMP Thu Aug 29 12:43:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Python 3.7.4
ChromeDriver 76.0.3809.68
Google Chrome 76.0.3809.132
```
``` bash
配置信息：
RE_VERSION = "1.1.105"
COOKIE_TYPE = 1
CHROME_PATH = "/usr/bin/chromedriver"
```
``` bash
错误信息：
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
cookie获取中
Traceback (most recent call last):
  File "/root/12306/run.py", line 20, in <module>
    run()
  File "/root/12306/run.py", line 8, in run
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 148, in main
    getDrvicesID(self)
  File "/root/12306/config/getCookie.py", line 19, in getDrvicesID
    driver = webdriver.Chrome(chrome_options=options, executable_path=TickerConfig.CHROME_PATH)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by testerSunshine** [comment]
加上这个试试
```
options = webdriver.ChromeOptions()
options.add_argument(‘–headless’)
options.add_argument(‘–disable-gpu’)
options.add_argument(‘–no-sandbox’)
```

**Comment by Alion548** [comment]
请问是修改getCookie.py这个文件吗？

**Comment by testerSunshine** [comment]
嗯

**Comment by CoXier** [comment]
仍然不行。另外你的

> 加上这个试试
> 
> ```
> options = webdriver.ChromeOptions()
> options.add_argument(‘–headless’)
> options.add_argument(‘–disable-gpu’)
> options.add_argument(‘–no-sandbox’)
> ```

仍然不行

**Comment by hldh214** [comment]
加完还需要作为参数传给 selenium
![image](https://user-images.githubusercontent.com/5501843/64932487-f97af600-d871-11e9-8a3d-a39e92dbbc33.png)
