### ISSUE TITLE
错误，mac操作系统

### ISSUE THREAD

**Issue by gmw-zjw** [testerSunshine/12306#322]
**描述问题**
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/Users/Sky/Desktop/12306/config/emailConf.py", line 4, in <module>
    import TickerConfig
  File "/Users/Sky/Desktop/12306/TickerConfig.py", line 9
SyntaxError: Non-ASCII character '\xe5' in file /Users/Sky/Desktop/12306/TickerConfig.py on line 9, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**环境信息**
 - mac 14.X
 - python3.7
 - 订票小助手版本 1.1.101

**额外的备注**
按照readme配置，但是报错

**Comment by fengmuhai** [comment]
在TickerConfig.py文件第一行加上：#coding=utf-8
