### ISSUE TITLE
print(f"url: {urls['req_url']}返回参数为空, 接口状态码: {response.status_code}"

### ISSUE THREAD

**Issue by dhlhd** [testerSunshine/12306#329]
**描述问题**
运行 sudo python run.py
然后出现如下错误：
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.pushbearConf import sendPushBear
  File "/mnt/hgfs/share/12306/config/pushbearConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/mnt/hgfs/share/12306/myUrllib/httpUtils.py", line 165
    print(f"url: {urls['req_url']}返回参数为空, 接口状态码: {response.status_code}"

**环境信息**
 - ubuntu
 - python3.7.1
 - 订票小助手版本 1.1.106

**Comment by testerSunshine** [comment]
https://github.com/testerSunshine/12306/issues/321
