### ISSUE TITLE
版本1.1.109运行直接报错

### ISSUE THREAD

**Issue by ChangWencai** [testerSunshine/12306#344]
# 软件版本
RE_VERSION = "1.1.109"

# 直接运行报错
cookie获取中
Traceback (most recent call last):
  File "D:/mycodes/12306/run.py", line 20, in <module>
    run()
  File "D:/mycodes/12306/run.py", line 8, in run
    select_ticket_info.select().main()
  File "D:\mycodes\12306\init\select_ticket_info.py", line 149, in main
    getDrvicesID(self)
  File "D:\mycodes\12306\config\getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "C:\Program Files\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Program Files\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Program Files\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service D:\export\opAdmin.exe unexpectedly exited. Status code was: 1

**Comment by ChangWencai** [comment]
是我chromedriver路径配置错误导致
