### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by dzf123** [testerSunshine/12306#345]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/daichongfa/GithubDownload/12306-master/config/serverchanConf.py", line 22
    sendServerChanUrls["req_url"] += f'{secret}.send'
                                                    ^
SyntaxError: invalid syntax

**Comment by testerSunshine** [comment]
dad76820cbeb454de6a8fd9d8c15757aa96b3583
