### ISSUE TITLE
错误ImportError: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by freesd** [testerSunshine/12306#349]
依赖好不容易弄好，运行又出现这个错误。
D:\UserDate\Desktop\12306>run.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helpe
r
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\imp.py", line
 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\imp.py", line
 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\UserDate\Desktop\12306\run.py", line 4, in <module>
    from init import select_ticket_info
  File "D:\UserDate\Desktop\12306\init\select_ticket_info.py", line 16, in <modu
le>
    from init.login import GoLogin
  File "D:\UserDate\Desktop\12306\init\login.py", line 12, in <module>
    from inter.GetRandCode import getRandCode
  File "D:\UserDate\Desktop\12306\inter\GetRandCode.py", line 4, in <module>
    from verify.localVerifyCode import verify
  File "D:\UserDate\Desktop\12306\verify\localVerifyCode.py", line 7, in <module
>
    from keras import models, backend
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\backend\load_backend.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helpe
r
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\imp.py", line
 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Gg\AppData\Local\Programs\Python\Python36\lib\imp.py", line
 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by testerSunshine** [comment]
tensorflow的问题
