### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Greyfoss7** [testerSunshine/12306#385]
**描述问题**
```
Permission denied
```
**重现步骤**
```
步骤一
```
**截图&日志**
cookie获取中
Traceback (most recent call last):
  File "/usr/lib/python3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/data/software/12306/init/select_ticket_info.py", line 151, in main
    getDrvicesID(self)
  File "/data/software/12306/config/getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "/usr/lib/python3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/lib/python3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**环境信息**
 - python3.6.1
 - 订票小助手版本 1.1.113

**额外的备注**

**Comment by yrong** [comment]
chmod +x webdriver

**Comment by PeterLiu77** [comment]
在哪里的webdriver呀

**Comment by Fanze0** [comment]
解决了吗 同样问题

**Comment by PeterLiu77** [comment]
有解决的吗，同步一下

**Comment by ALeftHanded** [comment]
ticketconfig文件 cookie type 置为 0

**Comment by Getthrough** [comment]
请看 TickerConfig.py 中的注释：
```
COOKIE_TYPE = 1
# 如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
```
前往上述网页下载对应 chromeDriver。下载完成后将 chromeDriver 所在的路径填写到 `CHROME_PATH` 中，我的配置：
```
COOKIE_TYPE = 1
# 如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
# chromedriver配置版本只要和chrome的大版本匹配就行
CHROME_PATH = "/Users/getthrough/Downloads/chromedriver"
```
再启动就 OK 了。

另外如 @ALeftHanded 所说，将 `COOKIE_TYPE = 1` 改为`COOKIE_TYPE = 0`也可以，无需配置 `CHROME_PATH`。

**Comment by shidesheng** [comment]
linux系统需要安装google-chrome和桌面环境，用普通用户登录桌面环境，启动应用。
