### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Cunese2020** [testerSunshine/12306#392]
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/cunese/Downloads/12306-master/config/serverchanConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/Users/cunese/Downloads/12306-master/myUrllib/httpUtils.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by peterxucai** [comment]
缺少requests模块， 安装一下： pip install requests
