### ISSUE TITLE
python3 run.py 无法正常执行在 cookie 这一步直接跳出

### ISSUE THREAD

**Issue by skiy** [testerSunshine/12306#400]
**描述问题**
```
执行 python3 run.py 报错，无法正常启动。
```
**重现步骤**
```
步骤一
```
**截图&日志**
![2019-09-19_16-45](https://user-images.githubusercontent.com/3362147/65228386-ef205c80-dafc-11e9-8e84-8a39aeee798d.png)

预售踩点时间:13:00:00
**************************************************
cookie获取中
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 155, in main
    getDrvicesID(self)
  File "/root/12306/config/getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**环境信息**
 - centos
 - python3.6
 - 订票小助手版本 1.1.114

**额外的备注**
- python3 是使用 yum install 安装的 python3.6
- centos 是 CentOS Linux release 7.4.1708 (Core)
- 腾讯云的云主机

**Comment by skiy** [comment]
[#issues/385](https://github.com/testerSunshine/12306/issues/385#issuecomment-531739406) 这边有说了。因为我是服务器的，没有 chrome 相关的工具，所以直接设置为 0 就可以了。
