### ISSUE TITLE
求解这是没安装模组吗

### ISSUE THREAD

**Issue by yuukicocoa** [testerSunshine/12306#402]
cookie获取中
Traceback (most recent call last):
  File "E:\programs\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "E:\programs\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "E:\programs\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "D:\12306-master\init\select_ticket_info.py", line 155, in main
    getDrvicesID(self)
  File "D:\12306-master\config\getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "E:\programs\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "E:\programs\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'S06-master' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by testerSunshine** [comment]
chrome路径
