### ISSUE TITLE
无法启动，请问错在那呀

### ISSUE THREAD

**Issue by liangzhdp** [testerSunshine/12306#410]
**描述问题**
```
>>> sudo python run.py
**************************************************
检查当前版本为: 1.1.114
检查当前python版本为：3.7.4，目前版本只支持3.6以上
12306刷票小助手，最后更新于2019.09.18，请勿作为商业用途，交流群号： 1群：286271084(已满)

 8群: 620629239(未满)

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/home/zhi/12306/tl/12306/init/select_ticket_info.py", line 37, in __init__
    self.get_ticket_info()
  File "/home/zhi/12306/tl/12306/init/select_ticket_info.py", line 76, in get_ticket_info
    f"当前配置：\n出发站：{TickerConfig.FROM_STATION}\n到达站：{TickerConfig.TO_STATION}\n车次: {','.join(TickerConfig.STATION_TRAINS) or '所有车次'}\n乘车日期：{','.join(TickerConfig.STATION_DATES)}\n坐席：{','.join(TickerConfig.SET_TYPE)}\n是否有票优先提交：{TickerConfig.IS_MORE_TICKET}\n乘车人：{TickerConfig.TICKET_PEOPLES}\n" \
TypeError: sequence item 0: expected str instance, int found
```
环境：archlinux

**Comment by lb0629** [comment]
想要字符串啊。你给了个int
