### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by m8076176** [testerSunshine/12306#412]
**描述问题**
```
gzj@gzj-PC:~/Downloads/12306-master$ sudo python3 run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/home/gzj/Downloads/12306-master/config/serverchanConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/home/gzj/Downloads/12306-master/myUrllib/httpUtils.py", line 7, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 -Linux
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
-

**Comment by ultimateHandsomeBoy666** [comment]
没装fake-agent包吧

**Comment by m8076176** [comment]
安装了，还是不行

**Comment by sorker** [comment]
我也遇到了这个情况，我安装了

**Comment by sorker** [comment]
pip3 install fake_useragent
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: fake_useragent in /home/pi/.local/lib/python3.7/site-packages (0.1.11)

**Comment by sorker** [comment]
可是还是不行

**Comment by sorker** [comment]
> 安装了，还是不行

请问你解决了吗，怎么做的
