### ISSUE TITLE
win10 py3.7

### ISSUE THREAD

**Issue by zjp99** [testerSunshine/12306#423]
Traceback (most recent call last):
  File "D:/Downloads/12306-master/12306-master/run.py", line 20, in <module>
    run()
  File "D:/Downloads/12306-master/12306-master/run.py", line 8, in run
    select_ticket_info.select().main()
  File "D:\Downloads\12306-master\12306-master\init\select_ticket_info.py", line 155, in main
    getDrvicesID(self)
  File "D:\Downloads\12306-master\12306-master\config\getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "F:\software\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "F:\software\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "F:\software\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "F:\software\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
OSError: [WinError 87] 参数错误。

**Comment by tiger6** [comment]
参考这个问题:https://github.com/testerSunshine/12306/issues/159,
# 如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
# chromedriver配置版本只要和chrome的大版本匹配就行

**Comment by zjp99** [comment]
好的已解决




------------------ 原始邮件 ------------------
发件人: "tiger6"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 上午10:21
收件人: "testerSunshine/12306"<12306@noreply.github.com>;
抄送: "🌚🌚52Hz的老赵"<3238816982@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [testerSunshine/12306] win10 py3.7 (#423)




参考这个问题:#159,
 
如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
 
chromedriver配置版本只要和chrome的大版本匹配就行
