### ISSUE TITLE
Chromedriver报错终止:unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by Sudiaty** [testerSunshine/12306#424]
**描述问题**
运行后报错
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
**截图&日志**
```
cookie获取中
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/home/www/12306/init/select_ticket_info.py", line 155, in main
    getDrvicesID(self)
  File "/home/www/12306/config/getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
**环境信息**
 - ubuntu
 - python3.6.8
 - 订票小助手版本 1.1.114
 - Google-chrome : 77.0.3865.90
  > path : /usr/bin/google-chrome
 - ChromeDriver : 77.0.3865.40
  > path : /usr/local/share/chromedriver
  > path : /usr/bin/chromedriver (ln)

**Comment by Sudiaty** [comment]
# 问题原因
服务器没有图形化界面
运行错误
# 解决办法
修改config/getCookie.py,向webdriver.chrome()函数传入额外参数，关闭沙箱模式、无头运行chrome。代码如下图所示
```
 15         from selenium import webdriver
 16         options= webdriver.ChromeOptions()
 17         options.add_argument('--headless')
 18         options.add_argument('--no-sandbox')
 19   
 20         cookies = []
 21         driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH,chrome_options=options)

```
