### ISSUE TITLE
运行报这个错误DLL load failed with error code 3221225501

### ISSUE THREAD

**Issue by seualphagit** [testerSunshine/12306#435]
环境Win7， python3.7.4
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from init import select_ticket_info
  File "D:\Project\PythonProject\12306\init\select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "D:\Project\PythonProject\12306\init\login.py", line 12, in <module>
    from inter.GetRandCode import getRandCode
  File "D:\Project\PythonProject\12306\inter\GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "D:\Project\PythonProject\12306\verify\localVerifyCode.py", line 9, in <module>
    from keras import models, backend
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\__init__.py", line 6, in <modu
le>
    from . import conv_utils
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\conv_utils.py", line 9, in <mo
dule>
    from .. import backend as K
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\__init__.py", line 89, in <m
odule>
    from .tensorflow_backend import *
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line
 5, in <module>
    import tensorflow as tf
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 28, in <modu
le>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, i
n <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", l
ine 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_intern
al.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_intern
al.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\seuAlpha\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code 3221225501

**Comment by seualphagit** [comment]
各模块的版本
absl-py              0.8.0
astor                0.8.0
beautifulsoup4       4.5.3
bs4                  0.0.1
certifi              2019.9.11
chardet              3.0.4
cycler               0.10.0
fake-useragent       0.1.11
gast                 0.3.2
google-pasta         0.1.7
grpcio               1.24.0
h5py                 2.10.0
idna                 2.6
joblib               0.13.2
Keras                2.2.4
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.1
ntplib               0.3.3
numpy                1.17.2
opencv-python        4.1.1.26
Pillow               6.1.0
pip                  19.2.3
protobuf             3.9.2
pyparsing            2.4.2
python-dateutil      2.8.0
PyYAML               5.1.1
requests             2.18.4
scikit-learn         0.21.3
scipy                1.3.1
selenium             3.11.0
setuptools           41.2.0
six                  1.10.0
sklearn              0.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
urllib3              1.22
Werkzeug             0.16.0
wheel                0.33.6
wrapcache            1.0.8
wrapt                1.11.2

**Comment by zhengwei7** [comment]
pip install protobuf==3.6.0
