### ISSUE TITLE
权限拒绝

### ISSUE THREAD

**Issue by zzhangcong** [testerSunshine/12306#437]
**描述问题**
启动docker报错
```
**重现步骤**
```
步骤一
```
**截图&日志**
12306ticket | Traceback (most recent call last):
12306ticket |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
12306ticket |     stdin=PIPE)
12306ticket |   File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
12306ticket |     restore_signals, start_new_session)
12306ticket |   File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
12306ticket |     raise child_exception_type(errno_num, err_msg)
12306ticket | PermissionError: [Errno 13] Permission denied
12306ticket | 
12306ticket | During handling of the above exception, another exception occurred:
12306ticket | 
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 20, in <module>
12306ticket |     run()
12306ticket |   File "run.py", line 8, in run
12306ticket |     select_ticket_info.select().main()
12306ticket |   File "/usr/src/app/init/select_ticket_info.py", line 155, in main
12306ticket |     getDrvicesID(self)
12306ticket |   File "/usr/src/app/config/getCookie.py", line 17, in getDrvicesID
12306ticket |     driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
12306ticket |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
12306ticket |     self.service.start()
12306ticket |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
12306ticket |     os.path.basename(self.path), self.start_error_message)
12306ticket | selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
12306ticket | 
12306ticket exited with code 1

**环境信息**
 - CentOS Linux release 7.6.1810
 - python3.6.0以上版本
 - 订票小助手版本 1.1.114

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
PermissionError: [Errno 13] Permission denied，看这句话
