### ISSUE TITLE
有大佬遇到这个问题吗 启动时候报错了

### ISSUE THREAD

**Issue by wendell0316** [testerSunshine/12306#444]
**描述问题**
```
启动的时候.
```
**重现步骤**
```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/Users/wangdong/blog/12306-master/config/emailConf.py", line 4, in <module>
    import TickerConfig
  File "/Users/wangdong/blog/12306-master/TickerConfig.py", line 1
SyntaxError: Non-ASCII character '\xe5' in file /Users/wangdong/blog/12306-master/TickerConfig.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
**截图&日志**

**环境信息**
 - mac
 - python2.7.16
 - 订票小助手版本 1.1.101

**Comment by CHJoFrancis** [comment]
Python 3.6 - 3.7.4
Py版本有介绍
