### ISSUE TITLE
安装完依赖启动报错

### ISSUE THREAD

**Issue by zuohl** [testerSunshine/12306#447]
**描述问题**
```
安装完依赖运行报错
```
**重现步骤**
```
必现
```
**截图&日志**
Using TensorFlow backend.
Traceback (most recent call last):
  File "/mnt/d/developer/github/12306/run.py", line 4, in <module>
    from init import select_ticket_info
  File "/mnt/d/developer/github/12306/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/mnt/d/developer/github/12306/init/login.py", line 12, in <module>
    from inter.GetRandCode import getRandCode
  File "/mnt/d/developer/github/12306/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/mnt/d/developer/github/12306/verify/localVerifyCode.py", line 14, in <module>
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
**环境信息**
 - ubuntu1904
 - python3.7.3
 - 订票小助手版本 最新master分支
怀疑是tensorflow版本问题

**Comment by YinAoXiong** [comment]
是tf版本问题，原来requirements.txt没有对版本进行限制，然后就安装的是2.0.0。现在作者已经弄好了，你重新安装一下依赖就可以了
