### ISSUE TITLE
run.py 的时候出现Chrome的Driver错误

### ISSUE THREAD

**Issue by hpeiyan** [testerSunshine/12306#457]
**描述问题**
```
程序运行的时候，出现Chrome的Driver Permission Error
```
**重现步骤**
```
sudo python run.py
```
**截图&日志**
```bash
cookie获取中
Traceback (most recent call last):
  File "/anaconda3/envs/12306/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/anaconda3/envs/12306/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/envs/12306/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/Users/Yuseng/Documents/tools/12306-master/init/select_ticket_info.py", line 156, in main
    getDrvicesID(self)
  File "/Users/Yuseng/Documents/tools/12306-master/config/getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "/anaconda3/envs/12306/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/anaconda3/envs/12306/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: '' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
**环境信息**
 - Mac Os
 - python3.6.9
 - 订票小助手版本 1.1.114

**Comment by xynu617** [comment]
直接python run.py   不用加sudo试试，我用Ubuntu也是加sudo就报错，不加就没问题

**Comment by w550515513** [comment]
chmod +x webdriver
