### ISSUE TITLE
本地打码配置问题

### ISSUE THREAD

**Issue by SWXP** [testerSunshine/12306#468]
**描述问题**
```
将参数设置为2后，运行run.py报错
```
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from init import select_ticket_info
  File "/opt/12306-master/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/opt/12306-master/init/login.py", line 12, in <module>
    from inter.GetRandCode import getRandCode
  File "/opt/12306-master/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/opt/12306-master/verify/localVerifyCode.py", line 7, in <module>
    import cv2
  File "/opt/python3.6/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
请问有没有具体的配置过程呢？

**Comment by JerryJian** [comment]
请问，这个问题有解决方法吗，同样的问题，谢谢
```
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/home/jerry/12306/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/home/jerry/12306/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/home/jerry/12306/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/home/jerry/12306/verify/localVerifyCode.py", line 7, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

**Comment by JerryJian** [comment]
Ubuntu 18.04 解决了问题，安装依赖环境就好了：

```
sudo apt install libopencv-dev
```
