### ISSUE TITLE
win10运行环境异常问题

### ISSUE THREAD

**Issue by ChanaLii** [testerSunshine/12306#478]
**描述问题**
cookie获取中
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "C:\Users\To Kill a MockinBird\Desktop\临时文件\12306-master\init\select_ticket_info.py", line 146, in main
    getDrvicesID(self)
  File "C:\Users\To Kill a MockinBird\Desktop\临时文件\12306-master\config\getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "C:\Users\To Kill a MockinBird\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\To Kill a MockinBird\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\To Kill a MockinBird\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\To Kill a MockinBird\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**重现步骤**
```
#Step1 安装python36(64位)
#Step2 安装requirement.txt 提及的组件
#Step3 运行python run.py

```
**截图&日志**

**环境信息**
 - windows10
 - python3.6.8rc1
 - 订票小助手版本 v1.1.117

**额外信息**
- 安装32位的python能解决“OSError: [WinError 193] %1 不是有效的 Win32 应用程序。”该问题，但会无法安装tensorflow

**Comment by 372620040** [comment]
我也遇到了这个
`cookie获取中
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "D:\Anaconda\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "e:\python\12306\init\select_ticket_info.py", line 156, in main
    getDrvicesID(self)
  File "e:\python\12306\config\getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "D:\Anaconda\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by 995754346** [comment]
> 我也遇到了这个
> `cookie获取中
> 跟踪信息（最近一次通话最近）：
> 文件“ D：\ Anaconda \ lib \ site-packages \ selenium \ webdriver \ common \ service.py”，第76行，位于start
> stdin = PIPE中
> 文件“ D：\ Anaconda \ lib \ subprocess.py ”，行775，在**init**
> restore_signals中，start_new_session）
> 文件“ D：\ Anaconda \ lib \ subprocess.py”，行1178，在_execute_child
> startupinfo中）
> FileNotFoundError：[WinError 2]系统找不到指定的文件。
> 
> 在处理上述异常期间，发生了另一个异常：
> 
> 追溯（最近一次通话最后一次）：
> 在
> run（）中的文件“ run.py”，第20行，在运行中
> 文件“ run.py”的第8行，
> select_ticket_info.select（）。main（）
> 文件，“ e：\ python \ 12306 \ init \ select_ticket_info.py”，第156行，位于主
> getDrvicesID（self）
> 文件“ e：\ python \ 12306 \ config \ getCookie.py”，第17行，位于getDrvicesID
> 驱动程序= webdriver.Chrome（executable_path = TickerConfig.CHROME_PATH ）**init** self.service.start（）中的 文件“ D：\ Anaconda \ lib \ site-packages \
> selenium \ webdriver \ chrome \ webdriver.py”，第68行，文件“ D：\ Anaconda \ lib \ site-packages \ selenium \ webdriver \ common \ service.py“，第83行，位于开始 os.path.basename（self.path），self.start_error_message）****
> 
> 
> 
> selenium.common.exceptions.WebDriverException：消息：“ chromedriver”可执行文件必须位于PATH中。请参阅[https：// sites.google.com / a / chromium.org / chromedriver / home`](https://sites.google.com/a/chromium.org/chromedriver/home%60)

我遇到了和你一样的问题，请问你解决了吗

**Comment by imyip** [comment]
CHROME_PATH 参数需要配置你chromedriver的路径

**Comment by 995754346** [comment]
谢谢，我已经在交流群里得到解惑，可以正常运行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"imyip"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 下午3:11
收件人:&nbsp;"testerSunshine/12306"<12306@noreply.github.com&gt;;
抄送:&nbsp;"星愿lzy"<995754346@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [testerSunshine/12306] win10运行环境异常问题 (#478)




CHROME_PATH 参数需要配置你chromedriver的路径
