### ISSUE TITLE
docker 运行,centos 已安装 chromeDriver , cookie获取中一直报 FileNotFoundError: [Errno 2] No such file or directory: '/home/12306/chromedriver': '/home/12306/chromedriver'

### ISSUE THREAD

**Issue by benjious** [testerSunshine/12306#480]
**描述问题**
```
用  ./docker.sh run 启动过程中出现  cookie获取中一直报 FileNotFoundError: [Errno 2] No such file or directory: '/home/12306/chromedriver': '/home/12306/chromedriver' 

```
**重现步骤**
```
已安装了 chromeDriver , 且该路径下存在 chromedriver
```
**截图&日志**
```
12306ticket | cookie获取中
12306ticket | /usr/local/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
12306ticket |   warnings.warn('No training configuration found in save file: '
12306ticket | Traceback (most recent call last):
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
12306ticket |     stdin=PIPE)
12306ticket |   File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
12306ticket |     restore_signals, start_new_session)
12306ticket |   File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
12306ticket |     raise child_exception_type(errno_num, err_msg, err_filename)
12306ticket | FileNotFoundError: [Errno 2] No such file or directory: '/home/12306/chromedriver': '/home/12306/chromedriver'
12306ticket | 
12306ticket | During handling of the above exception, another exception occurred:
12306ticket | 
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 20, in <module>
12306ticket |     run()
12306ticket |   File "run.py", line 8, in run
12306ticket |     select_ticket_info.select().main()
12306ticket |   File "/usr/src/app/init/select_ticket_info.py", line 156, in main
12306ticket |     getDrvicesID(self)
12306ticket |   File "/usr/src/app/config/getCookie.py", line 25, in getDrvicesID
12306ticket |     idriver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
12306ticket |     self.service.start()
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
12306ticket |     os.path.basename(self.path), self.start_error_message)
12306ticket | selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
12306ticket | 
12306ticket exited with code 1

```
后来改在 /usr/bin 路径下也不行  
```
12306ticket | FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/chromedriver': '/usr/bin/chromedriver'

```
**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by benjious** [comment]
使用方式 3 软件就可以运行了
