### ISSUE TITLE
selenium开启ChromeDriver失败

### ISSUE THREAD

**Issue by ToBeTree** [testerSunshine/12306#498]
**描述问题**
```
selenium开启ChromeDriver失败
```
**重现步骤**
```
配置好全部信息后，执行`sudo python run.py`
在cookie获取中报错
已添加可执行权限，尝试在Chromedriver配置中增加

options.add_argument('--disable-gpu')
options.add_argument("--disable-dev-shm-usage")

依然报错
```
**截图&日志**
```
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "/Users/xxx/dev/python/12306/init/select_ticket_info.py", line 156, in main
    getDrvicesID(self)
  File "/Users/xxx/dev/python/12306/config/getCookie.py", line 27, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH,chrome_options=options)
  File "/Users/xxx/.virtualenvs/ticket/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/xxx/.virtualenvs/ticket/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/xxx/.virtualenvs/ticket/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/xxx/.virtualenvs/ticket/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/xxx/.virtualenvs/ticket/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/local/bin/chromedriver is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
**环境信息**
 - mac
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by ijunfly** [comment]
同样的问题，+1

**Comment by linxs953** [comment]
同样的问题 + 1

**Comment by rilweic** [comment]
同样的问题 + 1

**Comment by bigbigbigfish** [comment]
使用docker跑。把Dockerfile37 修改为Dockerfile，然后，sudo ./docker.sh run
![屏幕快照 2019-12-15 下午9 54 23](https://user-images.githubusercontent.com/9393513/70863674-8757a180-1f85-11ea-868d-cbc04e811dbf.png)

**Comment by sophiejjjj** [comment]
同样的问题 window10

**Comment by yckyos261** [comment]
同样的问题 mac 14.6 ；之前是能用的，但是pull了下代码就不能用了。

**Comment by yckyos261** [comment]
目前 pull request 里面有个代码 按照那个该下 就能用了。

**Comment by yckyos261** [comment]
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79

**Comment by ThreeStonesLee** [comment]
大佬这个问题解决了吗？我在MAC上也是这个问题，求解答

**Comment by xiafenglovemilan** [comment]
同样的问题，centos7

**Comment by nakedno19** [comment]
same problem in centos7
