### ISSUE TITLE
fake_useragent failed

### ISSUE THREAD

**Issue by linuxisgod** [testerSunshine/12306#507]
**描述问题**
``` use cache server失败
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```python run.py
**截图&日志**
当前配置：
出发站：深圳北
到达站：荆州
车次: G1028
乘车日期：2020-01-21
坐席：二等座
是否有票优先提交：True
乘车人：['']
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 1
下单模式: 2
预售踩点时间:12:38:00
**************************************************
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\v_wbtli\AppData\Local\Programs\Python\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
**环境信息**
 - windows
 - python3.6.7
 - 订票小助手版本 1.1.117

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
多试试，你的网络问题

**Comment by caiqinglinbeihai** [comment]
环境:
windows10
python3.6.8

我也报这个错,  https://fake-useragent.herokuapp.com/browsers/0.1.11 在浏览器可以正常打开

解决办法:
通过浏览器下载, 保存为fake_useragent.json, 放到项目根目录 `项目/fake_useraget.json'
修改 项目/myUrllib/httpUtils.py
```
def _set_user_agent():
    try:
        fake_useragent_file = os.getcwd() + "/fake_useragent.json"
        user_agent = UserAgent(path=fake_useragent_file).random
        return user_agent
    except:
       ...
```
