### ISSUE TITLE
 from keras import models, backend

### ISSUE THREAD

**Issue by gohaku** [testerSunshine/12306#515]
**描述问题**
```
Using TensorFlow backend.
```
**重现步骤**
步骤1
pip intall -i 网址 -r 文件（安装好后修改配置）
步骤2
python run.py c
步骤3
python run.py r

**截图&日志**
Using TensorFlow backend.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "G:\12306-master\init\select_ticket_info.py", line 16, in <modul
e>
    from init.login import GoLogin
  File "G:\12306-master\init\login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "G:\12306-master\inter\GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "G:\12306-master\verify\localVerifyCode.py", line 9, in <module>

    from keras import models, backend
  File "D:\Python\lib\site-packages\keras\__init__.py", line 3, in <mod
ule>
    from . import utils
  File "D:\Python\lib\site-packages\keras\utils\__init__.py", line 6, i
n <module>
    from . import conv_utils
  File "D:\Python\lib\site-packages\keras\utils\conv_utils.py", line 9,
 in <module>
    from .. import backend as K
  File "D:\Python\lib\site-packages\keras\backend\__init__.py", line 89
, in <module>
    from .tensorflow_backend import *
  File "D:\Python\lib\site-packages\keras\backend\tensorflow_backend.py
", line 5, in <module>
    import tensorflow as tf
  File "D:\Python\lib\site-packages\tensorflow\__init__.py", line 28, i
n <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "D:\Python\lib\site-packages\tensorflow\python\__init__.py", lin
e 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "D:\Python\lib\site-packages\tensorflow\core\framework\graph_pb2
.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "D:\Python\lib\site-packages\google\protobuf\descriptor.py", lin
e 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: 找不到指定的程序。
**环境信息**
 - windows
 - python3.6.0
 - 订票小助手版本 1.1.101

**Comment by testerSunshine** [comment]
这个是tf 安装的问题
