### ISSUE TITLE
1.2.002 运行出错 run.py c 命令，请问如何解决？

### ISSUE THREAD

**Issue by Nisemono23** [testerSunshine/12306#520]
Traceback (most recent call last):
  File "D:\12306\12306-master\run.py", line 29, in <module>
    from agency.cdn_utils import filterCdn
  File "D:\12306\12306-master\agency\cdn_utils.py", line 32
    print(f"鍔犲叆cdn: {cdn}")

**Comment by ofcZsgj** [comment]
我在mac下结果类似😂
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from agency.cdn_utils import filterCdn
  File "/Users/zsgj/Documents/Tools/12306/agency/cdn_utils.py", line 34
    print(f"加入cdn: {cdn}")
