### ISSUE TITLE
ModuleNotFoundError: No module named 'fake_useragent'

### ISSUE THREAD

**Issue by BartSu** [testerSunshine/12306#530]
**描述问题**
```
没有fake_useragent的包
```
**重现步骤**
```
步骤一
python3 run.py c
```
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/Users/BartSu/Downloads/12306-master/init/select_ticket_info.py", line 11, in <module>
    from agency.cdn_utils import CDNProxy, open_cdn_file
  File "/Users/BartSu/Downloads/12306-master/agency/cdn_utils.py", line 10, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/Users/BartSu/Downloads/12306-master/myUrllib/httpUtils.py", line 8, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**环境信息**
 - MacOS 10.14.4
 - python3.6.8
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
No module named 'fake_useragent' 这句话贴百度

**Comment by zqdeepbluesky** [comment]
我也没有解决
