### ISSUE TITLE
登陆的时候偶发性报错

### ISSUE THREAD

**Issue by bambi2016** [testerSunshine/12306#552]
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 2
下单模式: 1
预售踩点时间:12:59:57
**************************************************
cookie获取中
需要验证码
下载验证码...
下载验证码成功
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
验证码识别坐标为184,77
184,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "/Users/wujianhua/allcode/python/12306/run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/wujianhua/allcode/python/12306/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/Users/wujianhua/allcode/python/12306/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/Users/wujianhua/allcode/python/12306/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/Users/wujianhua/allcode/python/12306/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/Users/wujianhua/allcode/python/12306/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bambi2016** [comment]
我已经对这个软件不抱希望了，不知道为什么会有这么多star，真正有解决问题的有几个？貌似没有

**Comment by LyonJiang** [comment]
这个问题有解决吗
