### ISSUE TITLE
启动运行报错

### ISSUE THREAD

**Issue by mychao** [testerSunshine/12306#553]
**描述问题**
```
正则解析报错
```
**重现步骤**
```
步骤一
```
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/admin/Documents/work/deploy/12306/init/select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "/Users/admin/Documents/work/deploy/12306/inter/LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
**环境信息**
 - mac
 - python3.7.15
- 订票小助手版本 1.2.004

**额外的备注**
- Add any other context about the problem here.

**Comment by xiafandeshen** [comment]
我也碰到同样的问题了 

@testerSunshine

**Comment by chenmin1992** [comment]
怎么关了? @mychao 解决了吗
