### ISSUE TITLE
版本更新到最新版后 docker下运行就报错

### ISSUE THREAD

**Issue by chankudo** [testerSunshine/12306#554]
检查当前版本为: 1.2.004
检查当前python版本为：3.7.5，目前版本只支持3.6以上
12306刷票小助手，最后更新于2019.09.18，请勿作为商业用途，交流群号： 1群：286271084(已满)
 2群：649992274(已满)
 3群：632501142(已满)
 4群: 606340519(已满)
 5群: 948526733(已满)
 7群: 660689659(已满)
 8群: 620629239(已满)
 6群: 608792930(未满)
 9群: 693035807(未满)

当前配置：
出发站：深圳
到达站：武汉
车次: 所有车次
乘车日期：2020-01-19
坐席：一等座,二等座
是否有票优先提交：True
乘车人：['吴兰兰']
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 2
下单模式: 2
预售踩点时间:12:59:57
**************************************************
cookie获取中

获取cookie: [{'RAIL_EXPIRATION': '1577190731999'}, {'RAIL_DEVICEID': 'YRZ7h2E5lcuIo0vgo7Br62mQ39GxnqkUtVfRzIclGxII8ivWjydxJER3SNaHL17XY8njsGXijL03s33OYZMVNLSgKCJTZ5gIdrBBictO99i-Gg5KcUdV5wsekPY2YXzo7up0OL8kOMEom6fJdiPEptRwm6g1tr87'}]
cookie获取完成
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.46288902162702605&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.46288902162702605&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.46288902162702605&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.46288902162702605&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/usr/src/app/init/login.py", line 121, in go_login
    result = getPassCodeNewOrderAndLogin1(session=self.session, imgType="login")
  File "/usr/src/app/inter/GetPassCodeNewOrderAndLogin.py", line 59, in getPassCodeNewOrderAndLogin1
    result = eval(codeImgUrlRsp.split("(")[1].split(")")[0]).get("image")
IndexError: list index out of range
root@a6cc163cd063:/usr/src/app# exit

**Comment by nosqlcoco** [comment]
同样的问题
