### ISSUE TITLE
返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by atetest** [testerSunshine/12306#573]
**************************************************
检查当前版本为: 1.2.004
检查当前python版本为：3.7.4，目前版本只支持3.6以上
.
.
.
cookie获取中

DevTools listening on ws://127.0.0.1:64159/devtools/browser/a4efd8fc-fc20-45e0-95d3-6138dbcfb279

获取cookie: [{'RAIL_DEVICEID': 'aGinohGpeL_mYlsIGZp0irRAGi-oDq4RoXDPO4cWf_NhmS4crsB1-aU1qeBePiYojcMmFlMb46euxnIqr_6dwotcas_8CT_zVKIWZTfsGVK1lmdq-kI9HxtbF7crkVj87EsBsvi7rDYOkaVGmOufZYWqZSZlmAK8'}, {'RAIL_EXPIRATION': '1577401741733'}]
cookie获取完成
需要验证码
下载验证码...
验证码获取失败
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 17 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
题目为['薯条']
1 跑步机
2 薯条
3 口哨
4 热水袋
5 热水袋
6 狮子
7 口哨
8 薯条
验证码识别坐标为112,77,256,149
112,77,256,149
验证码已经过期
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
题目为['海鸥']
1 护腕
2 档案袋
3 印章
4 印章
5 海报
6 海鸥
7 钟表
8 篮球
验证码识别坐标为112,149
112,149
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 17 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
题目为['樱桃']
1 高压锅
2 冰箱
3 冰箱
4 樱桃
5 高压锅
6 卷尺
7 啤酒
8 档案袋
验证码识别坐标为256,77
256,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 11 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
题目为['手掌印']
1 金字塔
2 老虎
3 棉棒
4 蜜蜂
5 金字塔
6 金字塔
7 话梅
8 手掌印
验证码识别坐标为256,149
256,149
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "C:\Users\lank_yang\Desktop\12306-master\run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "C:\Users\lank_yang\Desktop\12306-master\init\select_ticket_info.py", line 123, in main
    self.call_login()
  File "C:\Users\lank_yang\Desktop\12306-master\init\select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "C:\Users\lank_yang\Desktop\12306-master\init\login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "C:\Users\lank_yang\Desktop\12306-master\init\login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "C:\Users\lank_yang\Desktop\12306-master\myUrllib\httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "C:\Users\lank_yang\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lank_yang\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lank_yang\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by luoyudong593** [comment]
看历史issue

**Comment by luoyudong593** [comment]
我是这么解决的 ***使用chrome自己手动登录账号,先不用关闭***

**Comment by wangneal** [comment]
我的解决方法COOKIE_TYPE改为1，配置chromDriver，再次重启就OK了
