### ISSUE TITLE
Mac下使用使用selenium获取devicesID的问题

### ISSUE THREAD

**Issue by smallren101** [testerSunshine/12306#583]
**描述问题**
```
过滤非docker非Windows系统下，程序可执行性
```

**截图&日志**
```
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/renchangwei/Downloads/12306/init/select_ticket_info.py", line 122, in main
    getDrvicesID(self)
  File "/Users/renchangwei/Downloads/12306/config/getCookie.py", line 27, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH,chrome_options=options)
  File "/Users/renchangwei/.local/share/virtualenvs/12306-2U5SIo0l/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/renchangwei/.local/share/virtualenvs/12306-2U5SIo0l/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/renchangwei/.local/share/virtualenvs/12306-2U5SIo0l/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/renchangwei/.local/share/virtualenvs/12306-2U5SIo0l/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/renchangwei/.local/share/virtualenvs/12306-2U5SIo0l/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at /opt/google/chrome/google-chrome
```
**环境信息**
 - Mac
 - python3.6.8
 - 订票小助手版本 1.2.002

**额外的备注**
- 修改config/getCookie.py20行：
```
if os.name != 'nt' and os.name != "posix" and TickerConfig.CHROME_CHROME_PATH:
```

**Comment by linguo2625469** [comment]
谢谢

**Comment by ishen7** [comment]
👍有效

**Comment by SpaceLearner** [comment]
good

**Comment by sakayaPHP** [comment]
亲测有效

**Comment by ifyour** [comment]
@smallren101 提个 PR 吧，这个 Bug 需要修复 😅

**Comment by SUSTYuxiao** [comment]
> @smallren101 提个 PR 吧，这个 Bug 需要修复 😅

+1

**Comment by SCoulY** [comment]
有用

**Comment by smallren101** [comment]
这是一个针对Mac机下的方案，经过测试，在Mac下的docker中，获取到的os.name值，与Mac一致。
这是一个不够严谨的解决方案，只能起到临时解决的效果
``` 
🇨🇳  ~/tmp/app  docker exec -it network_api /bin/bash

root@9dfd835e2943:/app# python
Python 3.6.8 (default, Jun 11 2019, 01:16:11)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.name
'posix'
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
root@9dfd835e2943:/app# 

```

**Comment by smallren101** [comment]
[这个应该更好](https://github.com/testerSunshine/12306/pull/501/files/addacf0932afde920bade27894a93385550c8b36)
