### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Mfk759853063** [testerSunshine/12306#60]
➜  12306-master python run.py
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/Users/vbn/dev/python/12306-master/init/select_ticket_info.py", line 45, in __init__
    self.arrival_time, self.take_time = self.get_ticket_info()
  File "/Users/vbn/dev/python/12306-master/init/select_ticket_info.py", line 68, in get_ticket_info
    set_type = [seat_conf[x.encode("utf8")] for x in ticket_info_config["set"]["set_type"]]
KeyError: '\xe8\xbd\xaf\xe5\xba\xa7'

**Comment by testerSunshine** [comment]
配置文件写错了

**Comment by 1104049235** [comment]
我想知道为啥错了，二等座不对吗
