### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

### ISSUE THREAD

**Issue by xia-mi88** [testerSunshine/12306#601]
**描述问题**
```anacoda环境中，CDN刷新成功，server酱测试成功，但抢票程序运行出错

**重现步骤**
```conda create --name python34 python=3.4
git clone https://github.com/testerSunshine/12306.git
cd 12306
pip install -r requirements.txt
vi TickerConfig.py


步骤一
```配置serverChan（略）
步骤二

python3 run.py c
python3 run.py t
步骤三
python3 run.py r  #运行出错
**截图&日志**
(12306) [mina@oc1657727366 12306]$ python3 run.py r
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/home/mina/anaconda3/envs/12306/12306/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/home/mina/anaconda3/envs/12306/12306/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/home/mina/anaconda3/envs/12306/12306/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/home/mina/anaconda3/envs/12306/12306/verify/localVerifyCode.py", line 9, in <module>
    from keras import models, backend
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/mina/anaconda3/envs/12306/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/mina/anaconda3/envs/12306/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


**环境信息**
 - RHEL7.7
 - python3.7.4
 - 订票小助手版本 最新

**额外的备注**
- Add any other context about the problem here.

**Comment by TerrorbladeART** [comment]
本地跑吧  这个问题是因为 TensorFlow 调用底层指令问题好像 GLIBC 是底层系统关键模块 很难去修改，我linux上也是报这个问题

**Comment by zhanpengli** [comment]
conda create -n tfgpu tensorflow python=3.6.8
conda install tensorflow-gpu==1.13.1

**Comment by xia-mi88** [comment]
> 本地跑吧 这个问题是因为 TensorFlow 调用底层指令问题好像 GLIBC 是底层系统关键模块 很难去修改，我linux上也是报这个问题

你的意思是不在anaconda环境中跑？可是RHEL7.7自带python是2.7版本的哎，这个程序现在只支持3.6-3.7.4啊,我本地有些程序需要2.7，所以我才在隔离环境跑12306的

**Comment by TerrorbladeART** [comment]
> > 本地运行吧这个问题是因为TensorFlow初始化嵌套指令问题好像GLIBC是一直系统关键模块很难去修改，我linux上也是报这个问题
> 
> 你的意思是不在anaconda环境中跑？是RHEL7.7自带python是2.7版本的哎，这个程序现在只支持3.6-3.7.4啊，我本地有些程序需要2.7，所以我才在隔离环境跑12306的

你本地用anaconda创建一个新环境跑就行了 。。。linux上TensorFlow会出问题至少7.6以下的我都试过 我昨晚 在服务器上搭建打码器就这个报错。 看了很多问题依然无解。

**Comment by TerrorbladeART** [comment]
> > > 本地运行吧这个问题是因为TensorFlow初始化插入指令问题好像GLIBC是一直系统关键模块很难去修改，我linux上也是报这个问题
> > 
> > 
> > 你的意思是不在anaconda环境中跑？是RHEL7.7自带python是2.7版本的哎，这个程序现在只支持3.6-3.7.4啊，我本地某些程序需要2.7，所以我才在隔离环境跑12306的
> 
> 。Linux上的TensorFlow会出问题至少7.6以下的我都试过我昨晚在服务器上建造打码器就这个报错。看了很多问题依然无解。

本地用anaconda建个新环境即可

**Comment by xia-mi88** [comment]
> conda create -n tfgpu tensorflow python=3.6.8
> conda install tensorflow-gpu==1.13.1

还真可以了，看来是python版本喝TS不兼容啥的了，不名觉厉啊

**Comment by Happleasei** [comment]
也不一定，我也是conda环境下python报这个错，但是不用conda就行，python3.7.1，tensorflow-gpu==1.14.0
