### ISSUE TITLE
tensorflow 哪个版本能行啊， win10系统，一直报错，说找不到版本，哭了

### ISSUE THREAD

**Issue by anjina** [testerSunshine/12306#611]
**描述问题**
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by szychou** [comment]
用阿里云的镜像可以

**Comment by manyhelp** [comment]
`E:\code_taobao\12306>python3 run.py c
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from agency.cdn_utils import filterCdn
  File "E:\code_taobao\12306\agency\cdn_utils.py", line 10, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "E:\code_taobao\12306\myUrllib\httpUtils.py", line 8, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'`

**Comment by link-www** [comment]
> 用阿里云的当然可以

阿里云的链接应该怎么找

**Comment by tanliwei** [comment]
改成阿里云的[镜像](https://yq.aliyun.com/articles/652884)了，需要添加信任。
pip3 install -i http://mirrors.aliyun.com/pypi/simple/ -r requirements.txt  --trusted-host mirrors.aliyun.com

不过试了几个版本后还是不行。 1.14.0， 1.15.0  @szychou 请问 你用的哪个版本

**Comment by yangelar** [comment]
python版本3.6，且需要是**64位的**，安装python后升级pip

**Comment by link-www** [comment]
> python版本3.6，且需要是**64位的**，安装python后升级pip

pip版本19
python版本3.6.5 64位还是不行
