### ISSUE TITLE
登录时多次接口状态302后报IndexError: pop index out of range

### ISSUE THREAD

**Issue by ZaleJ** [testerSunshine/12306#619]
**描述问题**
```
多次接口状态302后报IndexError: pop index out of range
```
**重现步骤**
```
步骤一   装依赖、修改配置文件、运行python3 run.py c
步骤二   运行python3 run.py r
```
**截图&日志**
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "C:\Users\BUG季\IdeaProjects\12306\init\select_ticket_info.py", line 123, in main
    self.call_login()
  File "C:\Users\BUG季\IdeaProjects\12306\init\select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "C:\Users\BUG季\IdeaProjects\12306\init\login.py", line 119, in go_login
    if loginConf(self.session):
  File "C:\Users\BUG季\IdeaProjects\12306\inter\LoginConf.py", line 12, in loginConf
    loginConfRsp = session.httpClint.send(urls=loginConfUrl, data={})
  File "C:\Users\BUG季\IdeaProjects\12306\myUrllib\httpUtils.py", line 196, in send
    url_host = self.cdnList.pop(random.randint(0, 4))
IndexError: pop index out of range

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**Comment by ChenBinOnly** [comment]
老哥  解决了吗  我也遇到了这个问题

**Comment by RiverLi** [comment]
前几天我也遇到这个问题了。似乎是程序的问题。
`
                        if self.cdnList:
                            # 如果下单或者登陆出现cdn 302的情况，立马切换cdn
                            url_host = self.cdnList.pop(random.randint(0, 4))
                        continue
`
刚接触这个。我觉得这行代码改成：
if len(self.cdnList)>1:
可能可以。我自己试了一下。只帮我替补了一张。还不能确定拿到票。
这个cdnlist有点不太明白。总共那么多个cdn IP第一次过滤只剩70多个，后来302错误一个个剔除cdn IP，到最后只剩一个了。还剔除就不好了。所以我改成只剩一个就不剔除了。似乎还可以。这个cdnlist我没有太明白。是相当于proxy吗？作者能解释一下吗？
