### ISSUE TITLE
运行脚本报错：TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by hhhhhhhE** [testerSunshine/12306#622]
**描述问题**
```
运行脚本报错：TypeError: expected string or bytes-like object
```
**重现步骤**
```
步骤一：python3 run.py r
```
**截图&日志**
检查当前版本为: 1.2.004
检查当前python版本为：3.7.4，目前版本只支持3.6以上
12306刷票小助手，最后更新于2019.09.18，请勿作为商业用途，交流群号： 1群：286271084(已满)
 2群：649992274(已满)
 3群：632501142(已满)
 4群: 606340519(已满)
 5群: 948526733(已满)
 7群: 660689659(已满)
 8群: 620629239(已满)
 6群: 608792930(未满)
 9群: 693035807(未满)

当前配置：
出发站：杭州东
到达站：鞍山西
车次: G1228
乘车日期：2020-01-22
坐席：二等座
是否有票优先提交：True
乘车人：['张师赫']
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 2
下单模式: 2
预售踩点时间:12:59:57
**************************************************
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/zhangshihe/Downloads/12306/init/select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "/Users/zhangshihe/Downloads/12306/inter/LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
**环境信息**
 - macOS Mojave 10.14.6
 - python3.7.4
 - 订票小助手版本 1.2.004

**Comment by qinxiaokun** [comment]
同样的错误，怎么解决？应该是哪配置的问题

**Comment by inkoil** [comment]
网络不通吧，检查自己的公司网络是否需要设置代理

**Comment by hhhhhhhE** [comment]
> 网络不通吧，检查自己的公司网络是否需要设置代理

谢谢老铁 我检查下，另外还想请教一下，我的乘车人显示的格式是对的嘛？之前运行的时候突然提醒我联系人列表找不到乘车人

**Comment by mofeixiaobao** [comment]
把代理关掉。
