### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by alterem** [testerSunshine/12306#624]
**************************************************
url: /otn/leftTicket/init返回参数为空, 接口状态码: 302
url: /otn/leftTicket/init返回参数为空, 接口状态码: 302
url: /otn/leftTicket/init返回参数为空, 接口状态码: 302
url: /otn/leftTicket/init返回参数为空, 接口状态码: 302
cookie获取中
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/alterem/Documents/my-finishing/python/12306/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/Users/alterem/Documents/my-finishing/python/12306/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/Users/alterem/Documents/my-finishing/python/12306/init/login.py", line 119, in go_login
    if loginConf(self.session):
  File "/Users/alterem/Documents/my-finishing/python/12306/inter/LoginConf.py", line 12, in loginConf
    loginConfRsp = session.httpClint.send(urls=loginConfUrl, data={})
  File "/Users/alterem/Documents/my-finishing/python/12306/myUrllib/httpUtils.py", line 196, in send
    url_host = self.cdnList.pop(random.randint(0, 4))
IndexError: pop index out of range

**Comment by lastshusheng** [comment]
先过滤cdn了没？python run.py c

**Comment by GhyJn0** [comment]
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
url: /otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT返回参数为空, 接口状态码: 302
天津-亳州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT, 可以手动查询是否有票
正在第1次查询 随机停留时长：3.66 乘车日期: 2020-01-25 车次：k1622 下单无票 耗时：834.617ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT返回参数为空, 接口状态码: 302
天津-亳州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT, 可以手动查询是否有票
正在第2次查询 随机停留时长：4.46 乘车日期: 2020-01-25 车次：k1622 下单无票 耗时：866.229ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT返回参数为空, 接口状态码: 302
天津-亳州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT, 可以手动查询是否有票
正在第3次查询 随机停留时长：3.28 乘车日期: 2020-01-25 车次：k1622 下单无票 耗时：677.741ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT返回参数为空, 接口状态码: 302
天津-亳州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT, 可以手动查询是否有票
正在第4次查询 随机停留时长：4.75 乘车日期: 2020-01-25 车次：k1622 下单无票 耗时：746.494ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2020-01-25&leftTicketDTO.from_station=TJP&leftTicketDTO.to_station=BZH&purpose_codes=ADULT返回参数为空, 接口状态码: 302

**Comment by hongchaopan** [comment]
同样问题。更新RAIL_EXPIRATION 和RAIL_DEVICEID之后就好了（去你的浏览器找到12306网站新的cookies）
