### ISSUE TITLE
本地打码报错

### ISSUE THREAD

**Issue by quanhoucun** [testerSunshine/12306#625]
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/root/12306/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/root/12306/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/root/12306/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/root/12306/verify/localVerifyCode.py", line 7, in <module>
    import cv2
  File "/usr/local/python3/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libXext.so.6: cannot open shared object file: No such file or directory

**Comment by FYpanda** [comment]
需要安装libsm6和libxrender1
