### ISSUE TITLE
登陆url被封了,无法完成登陆,程序崩溃,重新加入cdn

### ISSUE THREAD

**Issue by nalanqingze** [testerSunshine/12306#636]
**描述问题**
```
登陆url被封了,无法完成登陆,程序崩溃,重新加入cdn
```
**截图&日志**
captcha    | INFO: Initialized TensorFlow Lite runtime.
ticket     | 验证码识别坐标为40,77,184,77
ticket     | 40,77,184,77
ticket     | 验证码通过,开始登录..
ticket     | url: /passport/web/login返回参数为空, 接口状态码: 302
ticket     | url: /passport/web/login返回参数为空, 接口状态码: 302
ticket     | url: /passport/web/login返回参数为空, 接口状态码: 302
ticket     | url: /passport/web/login返回参数为空, 接口状态码: 302
ticket     | url: /passport/web/login返回参数为空, 接口状态码: 302
ticket     | Traceback (most recent call last):
ticket     |   File "run.py", line 22, in <module>
ticket     |     select_ticket_info.select().main()
ticket     |   File "/usr/src/app/init/select_ticket_info.py", line 123, in main
ticket     |     self.call_login()
ticket     |   File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
ticket     |     self.login.go_login()
ticket     |   File "/usr/src/app/init/login.py", line 129, in go_login
ticket     |     uamtk = self.baseLogin(user, passwd)
ticket     |   File "/usr/src/app/init/login.py", line 66, in baseLogin
ticket     |     tresult = self.session.httpClint.send(logurl, loginData)
ticket     |   File "/usr/src/app/myUrllib/httpUtils.py", line 185, in send
ticket     |     response.content.decode() if isinstance(response.content, bytes) else response.content)
ticket     |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
ticket     |     return _default_decoder.decode(s)
ticket     |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
ticket     |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
ticket     |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
ticket     |     raise JSONDecodeError("Expecting value", s, err.value) from None
ticket     | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![image](https://user-images.githubusercontent.com/25921560/71499744-f2b24500-289c-11ea-8180-9ffa306ba4f1.png)

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by nalanqingze** [comment]
看到一个类似的问题,先暂时关闭
