### ISSUE TITLE
Linux（CentOS7）系统下docker构建项目，已成功抢到票，供大家参考。

### ISSUE THREAD

**Issue by LiuLiuniuniu** [testerSunshine/12306#644]
传送门：https://blog.liuhai.fun/post.html?id=57&index=true

这里是[Windows 10](https://github.com/testerSunshine/12306/issues/640)的方法。

**Comment by lyslys888** [comment]
当前ip: 59.83.232.50, 延时: 931.27
当前ip: 222.186.141.132, 延时: 931.425
当前ip: 118.203.202.222, 延时: 934.373
当前ip: 221.235.187.67, 延时: 935.31
当前ip: 113.16.208.78, 延时: 936.581
当前ip: 117.169.93.86, 延时: 947.199
当前ip: 150.138.169.121, 延时: 968.963
当前ip: 222.186.141.145, 延时: 977.416
当前ip: 125.77.130.247, 延时: 987.242
当前ip: 111.6.176.25, 延时: 989.738
当前ip: 118.123.233.31, 延时: 997.701
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/usr/src/app/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

docker下 报错了
环境：VMware虚拟机中Ubuntu19.10

**Comment by hhzrz** [comment]
> 当前ip: 59.83.232.50, 延时: 931.27
> 当前ip: 222.186.141.132, 延时: 931.425
> 当前ip: 118.203.202.222, 延时: 934.373
> 当前ip: 221.235.187.67, 延时: 935.31
> 当前ip: 113.16.208.78, 延时: 936.581
> 当前ip: 117.169.93.86, 延时: 947.199
> 当前ip: 150.138.169.121, 延时: 968.963
> 当前ip: 222.186.141.145, 延时: 977.416
> 当前ip: 125.77.130.247, 延时: 987.242
> 当前ip: 111.6.176.25, 延时: 989.738
> 当前ip: 118.123.233.31, 延时: 997.701
> Traceback (most recent call last):
> File "run.py", line 21, in
> from init import select_ticket_info
> File "/usr/src/app/init/select_ticket_info.py", line 16, in
> from init.login import GoLogin
> File "/usr/src/app/init/login.py", line 8, in
> from inter.GetRandCode import getRandCode
> File "/usr/src/app/inter/GetRandCode.py", line 6, in
> from verify.localVerifyCode import Verify
> File "/usr/src/app/verify/localVerifyCode.py", line 7, in
> import cv2
> ModuleNotFoundError: No module named 'cv2'
> 
> docker下 报错了
> 环境：VMware虚拟机中Ubuntu19.10

请仔细阅读readme文件。
参考#675
请将配置文件[TickerConfig.py](https://raw.githubusercontent.com/testerSunshine/12306/master/TickerConfig.py)中的`AUTO_CODE_TYPE`设置为`3`。

**Comment by cao-lianhui** [comment]
大佬问下你是在 "建议抢票" 的情况下抢到票的吗？用了多长时间

**Comment by lyslys888** [comment]
> 大佬问下你是在 "建议抢票" 的情况下抢到票的吗？用了多长时间

在 "建议抢票" 的情况下 什么意思
