### ISSUE TITLE
本地打码，tensorflow出现问题

### ISSUE THREAD

**Issue by x7y8z99** [testerSunshine/12306#649]
**描述问题**
```
本地打码，tensorflow出现问题
```
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/Users/dg/Downloads/12306-master/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/Users/dg/Downloads/12306-master/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/Users/dg/Downloads/12306-master/inter/GetRandCode.py", line 12, in <module>
    v = Verify()
  File "/Users/dg/Downloads/12306-master/verify/localVerifyCode.py", line 49, in __init__
    self.loadImgModel()
  File "/Users/dg/Downloads/12306-master/verify/localVerifyCode.py", line 60, in loadImgModel
    self.imgModel = models.load_model(PATH('../12306.image.model.h5'))
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/sequential.py", line 301, in from_config
    model.add(layer)
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])
  File "/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 883, in call
    output = self.activation(output)
  File "/anaconda3/lib/python3.6/site-packages/keras/activations.py", line 31, in softmax
    return K.softmax(x)
  File "/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3231, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'

**Comment by hhzrz** [comment]
请按照issue模版描述你的问题谢谢
