### ISSUE TITLE
登录失败302

### ISSUE THREAD

**Issue by faker011** [testerSunshine/12306#650]
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/usr/src/app/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/usr/src/app/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/usr/src/app/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by faker011** [comment]
在网页登录下就好了

**Comment by yezidelongshao** [comment]
登录了也没解决。。

**Comment by paozhuanyinyu** [comment]
我也302了

**Comment by yezidelongshao** [comment]
我最后切换了个网络成功了
