### ISSUE TITLE
日志报错了

### ISSUE THREAD

**Issue by Federico2014** [testerSunshine/12306#653]
**描述问题**
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```
**截图&日志**

验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
已设置本地打码服务器
验证码识别坐标为40,149
40,149
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
已设置本地打码服务器
验证码识别坐标为184,77
184,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/usr/src/app/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/usr/src/app/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/usr/src/app/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**环境信息**
 - Mac
- docker 环境
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Federico2014** [comment]
登录接口返回302是什么意思

**Comment by zodiacmcfly** [comment]
请参考#320

**Comment by sherry007** [comment]
https://github.com/testerSunshine/12306/issues/320#issuecomment-534383003
这位朋友的回复让我解决了302问题，建议你试一下
