### ISSUE TITLE
提示： expected string or bytes-like object，知道要改哪里？

### ISSUE THREAD

**Issue by NewOneTcm** [testerSunshine/12306#656]
**描述问题**
启动后，一会儿开始报错

**截图&日志**
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "D:\GreenSoft\N12306_\init\select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "D:\GreenSoft\N12306_\inter\LiftTicketInit.py", line 18, in reqLiftTicket
Init
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "D:\python3\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
**环境信息**
 - windows 7 x64
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Joseph669** [comment]
matchObj = re.search('var CLeftTicketUrl = '(.*)'', result, re.M|re.I);
外层的单引号改为双引号，改成下面这样子
matchObj = re.search("var CLeftTicketUrl = '(.*)'", result, re.M|re.I);

**Comment by hhzrz** [comment]
这个问题的原因是：做正则表达式匹配前没有检查匹配对象的类型。
前一个请求的返回结果正常的时候才是string值，而出错的时候是一个类似`{"code": 9999, "message": "重试次数达到上限"}`的dict值。
修复方法：#683
