### ISSUE TITLE
No module named 'wrapcache'

### ISSUE THREAD

**Issue by mn6932** [testerSunshine/12306#663]
D:\12306\12306>python run.py r
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "D:\12306\12306\init\select_ticket_info.py", line 10, in <module>
    import wrapcache
ModuleNotFoundError: No module named 'wrapcache'

**Comment by zhangzhengstrive** [comment]
pip install wrapcache
