### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by FrankAblert** [testerSunshine/12306#664]
Traceback (most recent call last):
  File ".\run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "E:\PythonProjects\12306\init\select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "E:\PythonProjects\12306\inter\LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "E:\usersofts\Python3.7\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by hhzrz** [comment]
PLEASE describe your problem as the issue template.

**Comment by BetaGo** [comment]
今天我也遇到了，时好时坏，目测可能是部分CDN节点的问题。
1. 尝试重新更新下CDN `python3 run.py c`，然后再运行 `python3 run.py r`;
2. 或者在配置里设置 `IS_CDN = 2` 关掉CDN。
