### ISSUE TITLE
mac下执行 python3 run.py c 报错什么问题

### ISSUE THREAD

**Issue by ismilesky** [testerSunshine/12306#669]
mac下执行 `python3 run.py c` 报错什么问题

```
12306-master python3 run.py c
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from agency.cdn_utils import filterCdn
  File "/Users/VS/Desktop/12306-master/agency/cdn_utils.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by eyea** [comment]
+1  :(

**Comment by Jeffchal** [comment]
同样问题，请问解决了嘛?

**Comment by dpmaycry** [comment]
同问 一模一样的报错

**Comment by luanweijie** [comment]
就没有一个类似npm install的命令可以install所有依赖么

**Comment by eyea** [comment]
+1 
缺少了对应模块，安装好后，记得重启下命令行，再次运行命令。
已经在跑了

**Comment by chen645800876** [comment]
> 就没有一个类似npm install的命令可以install所有依赖么

还真有这个命令，其实作者已经提到了
直接在项目根路径下执行下面这个命令即可
`pip install requirements.txt`

**Comment by ofcZsgj** [comment]
这是什么情况呀
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from agency.cdn_utils import filterCdn
  File "/Users/zsgj/Documents/Tools/12306/agency/cdn_utils.py", line 34
    print(f"加入cdn: {cdn}")

**Comment by ZengRed** [comment]
> 这是什么情况呀
> Traceback (most recent call last):
> File "run.py", line 29, in
> from agency.cdn_utils import filterCdn
> File "/Users/zsgj/Documents/Tools/12306/agency/cdn_utils.py", line 34
> print(f"加入cdn: {cdn}")

python版本不对，要python3

**Comment by hitechbeijing** [comment]
> 就没有一个类似npm install的命令可以install所有依赖么

看readme，pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt，-i参数指定pip镜像，-r参数指定依赖文本。

**Comment by kizimini** [comment]
安装了, 重启终端了, 不行啊... 
以下的命令都使用了, 都提示Requirement already satisfied
pip3 install -i pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
pip3 install requests

~/develop/study/12306   master ● ?  pip3 install requests                                                                                                        ✔  23:47:28
Requirement already satisfied: requests in /Library/Python/3.7/site-packages (2.18.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.7/site-packages (from requests) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/3.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/3.7/site-packages (from requests) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/3.7/site-packages (from requests) (1.22)
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ~/develop/study/12306   master ● ?  python3 run.py t                                                                                                             ✔  23:47:31
Traceback (most recent call last):
  File "run.py", line 25, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/********/develop/study/12306/config/serverchanConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/Users/********/develop/study/12306/myUrllib/httpUtils.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by MichaelMa666** [comment]
> 安装了, 重启终端了, 还是不行啊...
> 以下的命令都使用了, 都提示Requirement already satisfied
> pip3 install -i pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
> pip3 install requests
> 
> ~/develop/study/12306 master ? pip3 install requests
> Requirement already satisfied: requests in /Library/Python/3.7/site-packages (2.18.4)
> Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/3.7/site-packages (from requests) (2019.11.28)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/3.7/site-packages (from requests) (3.0.4)
> Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/3.7/site-packages (from requests) (2.6)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/3.7/site-packages (from requests) (1.22)
> You are using pip version 19.0.3, however version 19.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ~/develop/study/12306 master ? python3 run.py t
> Traceback (most recent call last):
> File "run.py", line 25, in
> from config.serverchanConf import sendServerChan
> File "/Users/xxxxxx/develop/study/12306/config/serverchanConf.py", line 4, in
> from myUrllib.httpUtils import HTTPClient
> File "/Users/xxxxxx/develop/study/12306/myUrllib/httpUtils.py", line 7, in
> import requests
> ModuleNotFoundError: No module named 'requests'

和你一样，不知道咋办，执行了pip3 install requests，还是提示ModuleNotFoundError: No module named 'requests'

**Comment by dishcheng** [comment]
同上
![image](https://user-images.githubusercontent.com/26062252/72506850-b0699b80-387d-11ea-8375-7fa836057a2f.png)

**Comment by dishcheng** [comment]
> 同上
> ![image](https://user-images.githubusercontent.com/26062252/72506850-b0699b80-387d-11ea-8375-7fa836057a2f.png)
> ![image](https://user-images.githubusercontent.com/26062252/72507154-51585680-387e-11ea-8384-e1c2ed2c2765.png)

老铁们，我可以了，因为服务器自带的是3.5，我后来装的3.7，执行的时候需要指定python3.7 run.py t就可以了
