### ISSUE TITLE
执行python3 run.py t报错

### ISSUE THREAD

**Issue by 18310120994** [testerSunshine/12306#698]
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    from config.emailConf import sendEmail
  File "/opt/12306-master/config/emailConf.py", line 4, in <module>
    import TickerConfig
  File "/opt/12306-master/TickerConfig.py", line 44
    TICKET_PEOPLES = [“xxx”]

**Comment by LXYTSOS** [comment]
TICKET_PEOPLES要填乘车人名字
