### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by Idealisten** [testerSunshine/12306#699]
**描述问题**
```
运行两分钟后出现bug
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/usr/src/app/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

```

**环境信息**
 - ubuntu18.04
 - python3.6.9
 - 订票小助手版本 1.1.101

**额外的备注**
pip install opencv-python后再次运行还是出现此错误

**Comment by LXYTSOS** [comment]
请安装OpenCV的Python版本，`pip install OpenCV-python`

**Comment by Idealisten** [comment]
把打码类型从2改成3就行了
