### ISSUE TITLE
  File "/usr/src/app/init/select_ticket_info.py", line 104, in station_table     from_station = station_name[from_station]

### ISSUE THREAD

**Issue by AspenBen** [testerSunshine/12306#706]
**描述问题**
```
Traceback (most recent call last):
  File "/usr/src/app/init/select_ticket_info.py", line 101, in station_table
    from_station = station_name[from_station.encode("utf8")]
KeyError: b'\xe8\x90\xa7\xe5\x8e\xbf'

```
**重现步骤**
```
步骤一
运行docker-compose up --build -d
从日志中发现报错
```
**截图&日志**
![image](https://user-images.githubusercontent.com/29369047/71711196-dc772c80-2e3a-11ea-826d-3ef52e6e8e28.png)

**环境信息**
 - Ubuntu18.04 服务器
 - p检查当前python版本为：3.7.6，目前版本只支持3.6以上
 - 订票小助手版本 1.1.101

**额外的备注**
- Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 128, in main
    from_station, to_station = self.station_table(TickerConfig.FROM_STATION, TickerConfig.TO_STATION)
  File "/usr/src/app/init/select_ticket_info.py", line 104, in station_table
    from_station = station_name[from_station]
KeyError: '萧县'
【萧县是我的始发地名称】

**Comment by AspenBen** [comment]
解决了 ，因为station_name.txt这个文件中没有关于萧县站的信息。这个站刚开没几天，这个station_name.txt文件需要更新下了
