### ISSUE TITLE
验证码登录不了

### ISSUE THREAD

**Issue by ios-study** [testerSunshine/12306#707]
**描述问题**
```
验证码登录不了
```
**重现步骤**
```
步骤一
```
**截图&日志**
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/xuhuizhan/Downloads/12306-master/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/Users/xuhuizhan/Downloads/12306-master/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/Users/xuhuizhan/Downloads/12306-master/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/Users/xuhuizhan/Downloads/12306-master/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/Users/xuhuizhan/Downloads/12306-master/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**环境信息**
 - mac
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by evilidol** [comment]
我也这个错误，不知道怎么解决？

**Comment by licoba** [comment]
+1
