### ISSUE TITLE
终端里跑找不到cdn list

### ISSUE THREAD

**Issue by haha50** [testerSunshine/12306#71]
正在同步时间，请耐心等待30秒左右
系统当前时间2019-01-04 08:44:58.92
sh: ntpdate: command not found
同步后时间:2019-01-04 08:44:58.93
Traceback (most recent call last):
  File "/Users/FAN/Desktop/12306_v2_武毓涵/run.py", line 15, in <module>
    run()
  File "/Users/FAN/Desktop/12306_v2_武毓涵/run.py", line 7, in run
    select_ticket_info.select().main()
  File "/Users/FAN/Desktop/12306_v2_武毓涵/init/select_ticket_info.py", line 175, in main
    self.cdn_certification()
  File "/Users/FAN/Desktop/12306_v2_武毓涵/init/select_ticket_info.py", line 160, in cdn_certification
    all_cdn = CDN.open_cdn_file()
  File "/Users/FAN/Desktop/12306_v2_武毓涵/agency/cdn_utils.py", line 55, in open_cdn_file
    with open("./cdn_list", "r") as f:
IOError: [Errno 2] No such file or directory: './cdn_list'

**Comment by testerSunshine** [comment]
你运行是在什么目录，更目录下是有这个文件么？

**Comment by haha50** [comment]
根目录下有啊，原有的文件夹结构没有改动

**Comment by haha50** [comment]
但是在在spyder里跑没问题

**Comment by ttdevs** [comment]
提了一个PR，应该可以解决这个问题
