### ISSUE TITLE
设置STATION_TRAINS = [D28]后，python3 run.py c，报错NameError: name 'D28' is not defined

### ISSUE THREAD

**Issue by xueyingmo** [testerSunshine/12306#714]
我通过pip install -r requirements.txt 安装了依赖项后，并配置了参数，其中
STATION_TRAINS = [D28]，运行python3 run.py c出现如下NameError: name 'D28' is not defined，具体为：
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
python3 run.py r
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/home/jingwei/12306-master/init/select_ticket_info.py", line 9, in <module>
    import TickerConfig
  File "/home/jingwei/12306-master/TickerConfig.py", line 18, in <module>
    STATION_TRAINS = [D28]
NameError: name 'D28' is not defined

```
**截图&日志**

**环境信息**
 - Ubuntu
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by andyqingliu** [comment]
STATION_TRAINS = ["D28"] 应该这样写。
