### ISSUE TITLE
配置chromedriver抓取cookie报错

### ISSUE THREAD

**Issue by mcu13321** [testerSunshine/12306#721]
**描述问题**
```
mac下运行docker通过chromedriver获取cookie报错，详细如下
```
**重现步骤**
```
1. COOKIE_TYPE=1
2. 下载chromedriver(79.0.3945.36)，放置根目录下
3. 运行docker-compose up --build -d
4. 运行docker logs --follow ticket
等待cdn节点加载完毕，登陆获取cookie时候报错如下
```
**截图&日志**
```
cookie获取中
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 122, in main
    getDrvicesID(self)
  File "/usr/src/app/config/getCookie.py", line 27, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH,chrome_options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/src/app/chromedriver'
```
![image](https://user-images.githubusercontent.com/12017476/71761045-52de6200-2f01-11ea-8906-d4c6e9441439.png)

**环境信息**
 - macOS Mojave 10.14.6
 - python3.7
 - Docker version 19.03.5, build 633a0ea
 - 订票小助手版本 1.2.004

**Comment by mcu13321** [comment]
不用自己下载，dockerfile里面配置好了，多此一举了。
