### ISSUE TITLE
这个问题怎么处理

### ISSUE THREAD

**Issue by wangtianshang** [testerSunshine/12306#729]
cookie获取中
需要验证码
下载验证码...
下载验证码成功
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
验证码识别坐标为184,77,256,77
184,77,256,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/root/12306/12306/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/root/12306/12306/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/root/12306/12306/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/root/12306/12306/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/root/12306/12306/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wangtianshang** [comment]
centos7.3
Python  3.6.8

**Comment by zcill** [comment]
这个是cookie过期了，重新在TickerConfig.py中填下
