### ISSUE TITLE
我的时这个报错，不知道怎么搞啊

### ISSUE THREAD

**Issue by ForeverFunk** [testerSunshine/12306#769]
我的时这个报错，不知道怎么搞啊
`url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
验证码识别坐标为184,77
184,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/usr/src/app/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/usr/src/app/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/usr/src/app/myUrllib/httpUtils.py", line 185, in send
    response.content.decode() if isinstance(response.content, bytes) else response.content)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(ticket) ubuntu@VM-0-7-ubuntu:~/buy_ticket/12306$ 
`

_Originally posted by @Hanoso in https://github.com/testerSunshine/12306/issues/320#issuecomment-568473456_

**Comment by ForeverFunk** [comment]
我也是报这个错，请问怎么解决啊？

**Comment by cick** [comment]
一样，重新搭建了下，然后发现各种登录不上和你差不多

`url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.362779661706671&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.362779661706671&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.362779661706671&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
验证码获取失败
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.9255817075633093&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
`

**Comment by panniyuyu** [comment]
看错误是配置文件有问题，没检查出来。。。。
