### ISSUE TITLE
expected string or bytes-like object

### ISSUE THREAD

**Issue by HuangQHH** [testerSunshine/12306#774]
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/opt/a12306/init/select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "/opt/a12306/inter/LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "/usr/local/python3/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
这个错误怎么修正呢。

**Comment by tubudan** [comment]
我的是因为开了V.P.N，cdn节点为0，就会出现该错误，关掉V.P.N就好了。
