### ISSUE TITLE
AttributeError: module 'TickerConfig' has no attribute 'USER'

### ISSUE THREAD

**Issue by kekekeke8** [testerSunshine/12306#800]
**按照视频正确配置了**
也下载了chromedriver配置了路径
不管设置1，2或者3总是出如下错误

cookie获取中
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/Users/.../Desktop/12306/12306/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/Users/.../Desktop/12306/12306/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/Users/../Desktop/12306/12306/init/login.py", line 114, in go_login
    user, passwd = TickerConfig.USER, TickerConfig.PWD
AttributeError: module 'TickerConfig' has no attribute 'USER'
```

**Comment by falyyyy** [comment]
TickerConfig.py里面USER和PWD不能设置为空，随便填写什么东西
