### ISSUE TITLE
验证码通过,开始登录后报错

### ISSUE THREAD

**Issue by xmzhangs** [testerSunshine/12306#820]
**描述问题**
```
验证码通过,开始登录.
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302

验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 123, in main
    self.call_login()
  File "/usr/src/app/init/select_ticket_info.py", line 117, in call_login
    self.login.go_login()
  File "/usr/src/app/init/login.py", line 129, in go_login
    uamtk = self.baseLogin(user, passwd)
  File "/usr/src/app/init/login.py", line 66, in baseLogin
    tresult = self.session.httpClint.send(logurl, loginData)
  File "/usr/src/app/myUrllib/httpUtils.py", line 196, in send
    url_host = self.cdnList.pop(random.randint(0, 4))
IndexError: pop index out of range
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Zhangdeli1993** [comment]
我也遇到,一样的问题,请问怎么解决

**Comment by yayaleslie** [comment]
一样，好难啊，楼主解决了吗
![image](https://user-images.githubusercontent.com/19268555/133753105-24e0c785-4157-4763-91a2-a127b689bc2c.png)

**Comment by abucraft** [comment]
登录接口/passport/web/login已经没法用了。会重定向到https://www.12306.cn/mormhweb/logFiles/error.html。

**Comment by abucraft** [comment]
参考https://github.com/testerSunshine/12306/issues/320
