### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lsz876** [testerSunshine/12306#823]
**描述问题**
```
使用requirements.txt安装的依赖，配置的是本地识别，运行时就会报错
```
**重现步骤**
```
python run.py r
```
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/home/lsz/workspace/12306/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/home/lsz/workspace/12306/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/home/lsz/workspace/12306/inter/GetRandCode.py", line 12, in <module>
    v = Verify()
  File "/home/lsz/workspace/12306/verify/localVerifyCode.py", line 49, in __init__
    self.loadImgModel()
  File "/home/lsz/workspace/12306/verify/localVerifyCode.py", line 60, in loadImgModel
    self.imgModel = models.load_model(PATH('../12306.image.model.h5'))
  File "/home/lsz/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/lsz/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
**环境信息**
 - Ubuntu20.4
 - python3.6.13
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by lsz876** [comment]
pip install 'h5py==2.10.0' --force-reinstall   可以解决此问题。https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi
