### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by JuneXg** [testerSunshine/12306#83]
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/home/ec2-user/12306-master/init/select_ticket_info.py", line 181, in main
    l.reqLiftTicketInit()
  File "/home/ec2-user/12306-master/inter/LiftTicketInit.py", line 14, in reqLiftTicketInit
    self.session.httpClint.send(urls)
  File "/home/ec2-user/12306-master/myUrllib/httpUtils.py", line 129, in send
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'urllib3'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 757, in run
  File "/home/ec2-user/12306-master/init/select_ticket_info.py", line 150, in cdn_req
  File "/home/ec2-user/12306-master/myUrllib/httpUtils.py", line 154, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exceptions'

**Comment by WangCaijun** [comment]
这个看样子是库没对上，按照Readme里执行pip install 那一串报错了吗？
