### ISSUE TITLE
/otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by deepfish123** [testerSunshine/12306#836]
登录成功运行一段时间就崩溃了, 系统mac系统
日志:
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/usr/src/app/init/select_ticket_info.py", line 216, in main
    c.sendChechFace()
  File "/usr/src/app/inter/ChechFace.py", line 68, in sendChechFace
    g.sendSuccessRate()
  File "/usr/src/app/inter/GetSuccessRate.py", line 32, in sendSuccessRate
    successRateRsp = self.session.httpClint.send(urls.get("getSuccessRate"), self.data_apr())
  File "/usr/src/app/myUrllib/httpUtils.py", line 196, in send
    url_host = self.cdnList.pop(random.randint(0, 4))
IndexError: pop index out of range

**Comment by JJery-web** [comment]
我也是。

验证码获取失败
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.17961886179937347&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302

**Comment by changzhenlin** [comment]
> 

解决了吗
