### ISSUE TITLE
登陆时，一直报错

### ISSUE THREAD

**Issue by junySong** [testerSunshine/12306#9]
刷新间隔：0.1
候选购买车次：K751,K282
未开始刷票间隔时间：0.3
僵尸票关小黑屋时长：3

********************
[*] 获取Cookie 
[*] 下载验证码... 
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/Users/Juny_Song/Downloads/12306-master/init/select_ticket_info.py", line 614, in main
    self.call_login()
  File "/Users/Juny_Song/Downloads/12306-master/init/select_ticket_info.py", line 611, in call_login
    go_login()
  File "/Users/Juny_Song/Downloads/12306-master/init/login.py", line 126, in go_login
    readImg()
  File "/Users/Juny_Song/Downloads/12306-master/init/login.py", line 42, in readImg
    randCode = DamatuApi(_get_yaml()["damatu"]["uesr"], _get_yaml()["damatu"]["pwd"], img_path).main()
  File "/Users/Juny_Song/Downloads/12306-master/damatuCode/damatuWeb.py", line 111, in main
    balance = self.getBalance()
  File "/Users/Juny_Song/Downloads/12306-master/damatuCode/damatuWeb.py", line 49, in getBalance
    res = self.post('d2Balance', data)
  File "/Users/Juny_Song/Downloads/12306-master/damatuCode/damatuWeb.py", line 39, in post
    response = requests.post(url, data)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9742): Max retries exceeded with url: http://api.dama2.com:7766/app/d2Balance (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f99e9d0>: Failed to establish a new connection: [Errno 61] Connection refused',)))
songjunhongdeMacBook-Pro:12306-master Juny_Song$

**Comment by junySong** [comment]
我都配置两天了，都还没有弄好，求大神指点下

**Comment by testerSunshine** [comment]
你是不是有代理啊？
https://segmentfault.com/q/1010000007245089/a-1020000007330530

**Comment by testerSunshine** [comment]
下载最新dev分支，已修改好
