### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by WangFinn** [testerSunshine/12306#97]
刷新间隔: 随机(1-3S)
购票方式：根据候选车次购买
候选购买车次：D1842,D1810
僵尸票关小黑屋时长: 5
下单接口: 2
下单模式: 2
预售踩点时间:13:00:00 
**************************************************
正在同步时间，请耐心等待30秒左右
系统当前时间2019-01-07 15:24:39.97
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
同步后时间:2019-01-07 15:24:39.98
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/home/finn/python/12306-master/init/select_ticket_info.py", line 179, in main
    self.cdn_certification()
  File "/home/finn/python/12306-master/init/select_ticket_info.py", line 164, in cdn_certification
    all_cdn = CDN.open_cdn_file()
  File "/home/finn/python/12306-master/agency/cdn_utils.py", line 135, in open_cdn_file
    for i in f.readlines():
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 7136: invalid start byte

**Comment by wcsnet** [comment]
同问，解决了吗？
